// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file trigger/trigger.proto (package blippy.trigger, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file trigger/trigger.proto.
 */
export const file_trigger_trigger: GenFile = /*@__PURE__*/
  fileDesc("ChV0cmlnZ2VyL3RyaWdnZXIucHJvdG8SDmJsaXBweS50cmlnZ2VyIvoBCgdUcmlnZ2VyEgoKAmlkGAEgASgJEhAKCGFnZW50X2lkGAIgASgJEgwKBG5hbWUYAyABKAkSDgoGcHJvbXB0GAQgASgJEhEKCWNyb25fZXhwchgFIAEoCRIPCgdlbmFibGVkGAYgASgIEi8KC25leHRfcnVuX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJoChRDcmVhdGVUcmlnZ2VyUmVxdWVzdBIQCghhZ2VudF9pZBgBIAEoCRIMCgRuYW1lGAIgASgJEg4KBnByb21wdBgDIAEoCRIRCgljcm9uX2V4cHIYBCABKAkSDQoFZGVsYXkYBSABKAkiHwoRR2V0VHJpZ2dlclJlcXVlc3QSCgoCaWQYASABKAkiJwoTTGlzdFRyaWdnZXJzUmVxdWVzdBIQCghhZ2VudF9pZBgBIAEoCSJBChRMaXN0VHJpZ2dlcnNSZXNwb25zZRIpCgh0cmlnZ2VycxgBIAMoCzIXLmJsaXBweS50cmlnZ2VyLlRyaWdnZXIiZAoUVXBkYXRlVHJpZ2dlclJlcXVlc3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIOCgZwcm9tcHQYAyABKAkSEQoJY3Jvbl9leHByGAQgASgJEg8KB2VuYWJsZWQYBSABKAgiIgoURGVsZXRlVHJpZ2dlclJlcXVlc3QSCgoCaWQYASABKAkiBwoFRW1wdHkyowMKDlRyaWdnZXJTZXJ2aWNlEk4KDUNyZWF0ZVRyaWdnZXISJC5ibGlwcHkudHJpZ2dlci5DcmVhdGVUcmlnZ2VyUmVxdWVzdBoXLmJsaXBweS50cmlnZ2VyLlRyaWdnZXISSAoKR2V0VHJpZ2dlchIhLmJsaXBweS50cmlnZ2VyLkdldFRyaWdnZXJSZXF1ZXN0GhcuYmxpcHB5LnRyaWdnZXIuVHJpZ2dlchJZCgxMaXN0VHJpZ2dlcnMSIy5ibGlwcHkudHJpZ2dlci5MaXN0VHJpZ2dlcnNSZXF1ZXN0GiQuYmxpcHB5LnRyaWdnZXIuTGlzdFRyaWdnZXJzUmVzcG9uc2USTgoNVXBkYXRlVHJpZ2dlchIkLmJsaXBweS50cmlnZ2VyLlVwZGF0ZVRyaWdnZXJSZXF1ZXN0GhcuYmxpcHB5LnRyaWdnZXIuVHJpZ2dlchJMCg1EZWxldGVUcmlnZ2VyEiQuYmxpcHB5LnRyaWdnZXIuRGVsZXRlVHJpZ2dlclJlcXVlc3QaFS5ibGlwcHkudHJpZ2dlci5FbXB0eUItWitnaXRodWIuY29tL2RzdG90aWpuL2JsaXBweS9pbnRlcm5hbC90cmlnZ2VyYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message blippy.trigger.Trigger
 */
export type Trigger = Message<"blippy.trigger.Trigger"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string agent_id = 2;
   */
  agentId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string prompt = 4;
   */
  prompt: string;

  /**
   * optional, empty if not set
   *
   * @generated from field: string cron_expr = 5;
   */
  cronExpr: string;

  /**
   * @generated from field: bool enabled = 6;
   */
  enabled: boolean;

  /**
   * optional, zero value if not set
   *
   * @generated from field: google.protobuf.Timestamp next_run_at = 7;
   */
  nextRunAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message blippy.trigger.Trigger.
 * Use `create(TriggerSchema)` to create a new message.
 */
export const TriggerSchema: GenMessage<Trigger> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 0);

/**
 * @generated from message blippy.trigger.CreateTriggerRequest
 */
export type CreateTriggerRequest = Message<"blippy.trigger.CreateTriggerRequest"> & {
  /**
   * @generated from field: string agent_id = 1;
   */
  agentId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string prompt = 3;
   */
  prompt: string;

  /**
   * optional, for scheduled triggers
   *
   * @generated from field: string cron_expr = 4;
   */
  cronExpr: string;

  /**
   * optional, for one-time delayed triggers (e.g., "5m", "1h")
   *
   * @generated from field: string delay = 5;
   */
  delay: string;
};

/**
 * Describes the message blippy.trigger.CreateTriggerRequest.
 * Use `create(CreateTriggerRequestSchema)` to create a new message.
 */
export const CreateTriggerRequestSchema: GenMessage<CreateTriggerRequest> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 1);

/**
 * @generated from message blippy.trigger.GetTriggerRequest
 */
export type GetTriggerRequest = Message<"blippy.trigger.GetTriggerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message blippy.trigger.GetTriggerRequest.
 * Use `create(GetTriggerRequestSchema)` to create a new message.
 */
export const GetTriggerRequestSchema: GenMessage<GetTriggerRequest> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 2);

/**
 * @generated from message blippy.trigger.ListTriggersRequest
 */
export type ListTriggersRequest = Message<"blippy.trigger.ListTriggersRequest"> & {
  /**
   * optional filter
   *
   * @generated from field: string agent_id = 1;
   */
  agentId: string;
};

/**
 * Describes the message blippy.trigger.ListTriggersRequest.
 * Use `create(ListTriggersRequestSchema)` to create a new message.
 */
export const ListTriggersRequestSchema: GenMessage<ListTriggersRequest> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 3);

/**
 * @generated from message blippy.trigger.ListTriggersResponse
 */
export type ListTriggersResponse = Message<"blippy.trigger.ListTriggersResponse"> & {
  /**
   * @generated from field: repeated blippy.trigger.Trigger triggers = 1;
   */
  triggers: Trigger[];
};

/**
 * Describes the message blippy.trigger.ListTriggersResponse.
 * Use `create(ListTriggersResponseSchema)` to create a new message.
 */
export const ListTriggersResponseSchema: GenMessage<ListTriggersResponse> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 4);

/**
 * @generated from message blippy.trigger.UpdateTriggerRequest
 */
export type UpdateTriggerRequest = Message<"blippy.trigger.UpdateTriggerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string prompt = 3;
   */
  prompt: string;

  /**
   * @generated from field: string cron_expr = 4;
   */
  cronExpr: string;

  /**
   * @generated from field: bool enabled = 5;
   */
  enabled: boolean;
};

/**
 * Describes the message blippy.trigger.UpdateTriggerRequest.
 * Use `create(UpdateTriggerRequestSchema)` to create a new message.
 */
export const UpdateTriggerRequestSchema: GenMessage<UpdateTriggerRequest> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 5);

/**
 * @generated from message blippy.trigger.DeleteTriggerRequest
 */
export type DeleteTriggerRequest = Message<"blippy.trigger.DeleteTriggerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message blippy.trigger.DeleteTriggerRequest.
 * Use `create(DeleteTriggerRequestSchema)` to create a new message.
 */
export const DeleteTriggerRequestSchema: GenMessage<DeleteTriggerRequest> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 6);

/**
 * @generated from message blippy.trigger.Empty
 */
export type Empty = Message<"blippy.trigger.Empty"> & {
};

/**
 * Describes the message blippy.trigger.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_trigger_trigger, 7);

/**
 * TriggerService manages autonomous triggers.
 *
 * @generated from service blippy.trigger.TriggerService
 */
export const TriggerService: GenService<{
  /**
   * @generated from rpc blippy.trigger.TriggerService.CreateTrigger
   */
  createTrigger: {
    methodKind: "unary";
    input: typeof CreateTriggerRequestSchema;
    output: typeof TriggerSchema;
  },
  /**
   * @generated from rpc blippy.trigger.TriggerService.GetTrigger
   */
  getTrigger: {
    methodKind: "unary";
    input: typeof GetTriggerRequestSchema;
    output: typeof TriggerSchema;
  },
  /**
   * @generated from rpc blippy.trigger.TriggerService.ListTriggers
   */
  listTriggers: {
    methodKind: "unary";
    input: typeof ListTriggersRequestSchema;
    output: typeof ListTriggersResponseSchema;
  },
  /**
   * @generated from rpc blippy.trigger.TriggerService.UpdateTrigger
   */
  updateTrigger: {
    methodKind: "unary";
    input: typeof UpdateTriggerRequestSchema;
    output: typeof TriggerSchema;
  },
  /**
   * @generated from rpc blippy.trigger.TriggerService.DeleteTrigger
   */
  deleteTrigger: {
    methodKind: "unary";
    input: typeof DeleteTriggerRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_trigger_trigger, 0);

