// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file trigger/trigger.proto (package blippy.trigger, syntax proto3)
/* eslint-disable */

import { TriggerService } from "./trigger_pb";

/**
 * @generated from rpc blippy.trigger.TriggerService.CreateTrigger
 */
export const createTrigger = TriggerService.method.createTrigger;

/**
 * @generated from rpc blippy.trigger.TriggerService.GetTrigger
 */
export const getTrigger = TriggerService.method.getTrigger;

/**
 * @generated from rpc blippy.trigger.TriggerService.ListTriggers
 */
export const listTriggers = TriggerService.method.listTriggers;

/**
 * @generated from rpc blippy.trigger.TriggerService.UpdateTrigger
 */
export const updateTrigger = TriggerService.method.updateTrigger;

/**
 * @generated from rpc blippy.trigger.TriggerService.DeleteTrigger
 */
export const deleteTrigger = TriggerService.method.deleteTrigger;
