// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file fsroot/fsroot.proto (package blippy.fsroot, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fsroot/fsroot.proto.
 */
export const file_fsroot_fsroot: GenFile = /*@__PURE__*/
  fileDesc("ChNmc3Jvb3QvZnNyb290LnByb3RvEg1ibGlwcHkuZnNyb290Iq0BCg5GaWxlc3lzdGVtUm9vdBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHBhdGgYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSLgoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiTgobQ3JlYXRlRmlsZXN5c3RlbVJvb3RSZXF1ZXN0EgwKBG5hbWUYASABKAkSDAoEcGF0aBgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCSImChhHZXRGaWxlc3lzdGVtUm9vdFJlcXVlc3QSCgoCaWQYASABKAkiHAoaTGlzdEZpbGVzeXN0ZW1Sb290c1JlcXVlc3QiSwobTGlzdEZpbGVzeXN0ZW1Sb290c1Jlc3BvbnNlEiwKBXJvb3RzGAEgAygLMh0uYmxpcHB5LmZzcm9vdC5GaWxlc3lzdGVtUm9vdCJaChtVcGRhdGVGaWxlc3lzdGVtUm9vdFJlcXVlc3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIMCgRwYXRoGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJIikKG0RlbGV0ZUZpbGVzeXN0ZW1Sb290UmVxdWVzdBIKCgJpZBgBIAEoCSIHCgVFbXB0eTKCBAoVRmlsZXN5c3RlbVJvb3RTZXJ2aWNlEmEKFENyZWF0ZUZpbGVzeXN0ZW1Sb290EiouYmxpcHB5LmZzcm9vdC5DcmVhdGVGaWxlc3lzdGVtUm9vdFJlcXVlc3QaHS5ibGlwcHkuZnNyb290LkZpbGVzeXN0ZW1Sb290ElsKEUdldEZpbGVzeXN0ZW1Sb290EicuYmxpcHB5LmZzcm9vdC5HZXRGaWxlc3lzdGVtUm9vdFJlcXVlc3QaHS5ibGlwcHkuZnNyb290LkZpbGVzeXN0ZW1Sb290EmwKE0xpc3RGaWxlc3lzdGVtUm9vdHMSKS5ibGlwcHkuZnNyb290Lkxpc3RGaWxlc3lzdGVtUm9vdHNSZXF1ZXN0GiouYmxpcHB5LmZzcm9vdC5MaXN0RmlsZXN5c3RlbVJvb3RzUmVzcG9uc2USYQoUVXBkYXRlRmlsZXN5c3RlbVJvb3QSKi5ibGlwcHkuZnNyb290LlVwZGF0ZUZpbGVzeXN0ZW1Sb290UmVxdWVzdBodLmJsaXBweS5mc3Jvb3QuRmlsZXN5c3RlbVJvb3QSWAoURGVsZXRlRmlsZXN5c3RlbVJvb3QSKi5ibGlwcHkuZnNyb290LkRlbGV0ZUZpbGVzeXN0ZW1Sb290UmVxdWVzdBoULmJsaXBweS5mc3Jvb3QuRW1wdHlCLFoqZ2l0aHViLmNvbS9kc3RvdGlqbi9ibGlwcHkvaW50ZXJuYWwvZnNyb290YgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message blippy.fsroot.FilesystemRoot
 */
export type FilesystemRoot = Message<"blippy.fsroot.FilesystemRoot"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message blippy.fsroot.FilesystemRoot.
 * Use `create(FilesystemRootSchema)` to create a new message.
 */
export const FilesystemRootSchema: GenMessage<FilesystemRoot> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 0);

/**
 * @generated from message blippy.fsroot.CreateFilesystemRootRequest
 */
export type CreateFilesystemRootRequest = Message<"blippy.fsroot.CreateFilesystemRootRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message blippy.fsroot.CreateFilesystemRootRequest.
 * Use `create(CreateFilesystemRootRequestSchema)` to create a new message.
 */
export const CreateFilesystemRootRequestSchema: GenMessage<CreateFilesystemRootRequest> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 1);

/**
 * @generated from message blippy.fsroot.GetFilesystemRootRequest
 */
export type GetFilesystemRootRequest = Message<"blippy.fsroot.GetFilesystemRootRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message blippy.fsroot.GetFilesystemRootRequest.
 * Use `create(GetFilesystemRootRequestSchema)` to create a new message.
 */
export const GetFilesystemRootRequestSchema: GenMessage<GetFilesystemRootRequest> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 2);

/**
 * @generated from message blippy.fsroot.ListFilesystemRootsRequest
 */
export type ListFilesystemRootsRequest = Message<"blippy.fsroot.ListFilesystemRootsRequest"> & {
};

/**
 * Describes the message blippy.fsroot.ListFilesystemRootsRequest.
 * Use `create(ListFilesystemRootsRequestSchema)` to create a new message.
 */
export const ListFilesystemRootsRequestSchema: GenMessage<ListFilesystemRootsRequest> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 3);

/**
 * @generated from message blippy.fsroot.ListFilesystemRootsResponse
 */
export type ListFilesystemRootsResponse = Message<"blippy.fsroot.ListFilesystemRootsResponse"> & {
  /**
   * @generated from field: repeated blippy.fsroot.FilesystemRoot roots = 1;
   */
  roots: FilesystemRoot[];
};

/**
 * Describes the message blippy.fsroot.ListFilesystemRootsResponse.
 * Use `create(ListFilesystemRootsResponseSchema)` to create a new message.
 */
export const ListFilesystemRootsResponseSchema: GenMessage<ListFilesystemRootsResponse> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 4);

/**
 * @generated from message blippy.fsroot.UpdateFilesystemRootRequest
 */
export type UpdateFilesystemRootRequest = Message<"blippy.fsroot.UpdateFilesystemRootRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message blippy.fsroot.UpdateFilesystemRootRequest.
 * Use `create(UpdateFilesystemRootRequestSchema)` to create a new message.
 */
export const UpdateFilesystemRootRequestSchema: GenMessage<UpdateFilesystemRootRequest> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 5);

/**
 * @generated from message blippy.fsroot.DeleteFilesystemRootRequest
 */
export type DeleteFilesystemRootRequest = Message<"blippy.fsroot.DeleteFilesystemRootRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message blippy.fsroot.DeleteFilesystemRootRequest.
 * Use `create(DeleteFilesystemRootRequestSchema)` to create a new message.
 */
export const DeleteFilesystemRootRequestSchema: GenMessage<DeleteFilesystemRootRequest> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 6);

/**
 * @generated from message blippy.fsroot.Empty
 */
export type Empty = Message<"blippy.fsroot.Empty"> & {
};

/**
 * Describes the message blippy.fsroot.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_fsroot_fsroot, 7);

/**
 * @generated from service blippy.fsroot.FilesystemRootService
 */
export const FilesystemRootService: GenService<{
  /**
   * @generated from rpc blippy.fsroot.FilesystemRootService.CreateFilesystemRoot
   */
  createFilesystemRoot: {
    methodKind: "unary";
    input: typeof CreateFilesystemRootRequestSchema;
    output: typeof FilesystemRootSchema;
  },
  /**
   * @generated from rpc blippy.fsroot.FilesystemRootService.GetFilesystemRoot
   */
  getFilesystemRoot: {
    methodKind: "unary";
    input: typeof GetFilesystemRootRequestSchema;
    output: typeof FilesystemRootSchema;
  },
  /**
   * @generated from rpc blippy.fsroot.FilesystemRootService.ListFilesystemRoots
   */
  listFilesystemRoots: {
    methodKind: "unary";
    input: typeof ListFilesystemRootsRequestSchema;
    output: typeof ListFilesystemRootsResponseSchema;
  },
  /**
   * @generated from rpc blippy.fsroot.FilesystemRootService.UpdateFilesystemRoot
   */
  updateFilesystemRoot: {
    methodKind: "unary";
    input: typeof UpdateFilesystemRootRequestSchema;
    output: typeof FilesystemRootSchema;
  },
  /**
   * @generated from rpc blippy.fsroot.FilesystemRootService.DeleteFilesystemRoot
   */
  deleteFilesystemRoot: {
    methodKind: "unary";
    input: typeof DeleteFilesystemRootRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_fsroot_fsroot, 0);

