// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file fsroot/fsroot.proto (package blippy.fsroot, syntax proto3)
/* eslint-disable */

import { FilesystemRootService } from "./fsroot_pb";

/**
 * @generated from rpc blippy.fsroot.FilesystemRootService.CreateFilesystemRoot
 */
export const createFilesystemRoot = FilesystemRootService.method.createFilesystemRoot;

/**
 * @generated from rpc blippy.fsroot.FilesystemRootService.GetFilesystemRoot
 */
export const getFilesystemRoot = FilesystemRootService.method.getFilesystemRoot;

/**
 * @generated from rpc blippy.fsroot.FilesystemRootService.ListFilesystemRoots
 */
export const listFilesystemRoots = FilesystemRootService.method.listFilesystemRoots;

/**
 * @generated from rpc blippy.fsroot.FilesystemRootService.UpdateFilesystemRoot
 */
export const updateFilesystemRoot = FilesystemRootService.method.updateFilesystemRoot;

/**
 * @generated from rpc blippy.fsroot.FilesystemRootService.DeleteFilesystemRoot
 */
export const deleteFilesystemRoot = FilesystemRootService.method.deleteFilesystemRoot;
