// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file agent/agent.proto (package blippy.agent, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file agent/agent.proto.
 */
export const file_agent_agent: GenFile = /*@__PURE__*/
  fileDesc("ChFhZ2VudC9hZ2VudC5wcm90bxIMYmxpcHB5LmFnZW50IvoBCgVBZ2VudBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhUKDXN5c3RlbV9wcm9tcHQYBCABKAkSFQoNZW5hYmxlZF90b29scxgFIAMoCRIlCh1lbmFibGVkX25vdGlmaWNhdGlvbl9jaGFubmVscxgGIAMoCRIuCgpjcmVhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBINCgVtb2RlbBgJIAEoCSKbAQoSQ3JlYXRlQWdlbnRSZXF1ZXN0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSFQoNc3lzdGVtX3Byb21wdBgDIAEoCRIVCg1lbmFibGVkX3Rvb2xzGAQgAygJEiUKHWVuYWJsZWRfbm90aWZpY2F0aW9uX2NoYW5uZWxzGAUgAygJEg0KBW1vZGVsGAYgASgJIh0KD0dldEFnZW50UmVxdWVzdBIKCgJpZBgBIAEoCSITChFMaXN0QWdlbnRzUmVxdWVzdCI5ChJMaXN0QWdlbnRzUmVzcG9uc2USIwoGYWdlbnRzGAEgAygLMhMuYmxpcHB5LmFnZW50LkFnZW50IqcBChJVcGRhdGVBZ2VudFJlcXVlc3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIVCg1zeXN0ZW1fcHJvbXB0GAQgASgJEhUKDWVuYWJsZWRfdG9vbHMYBSADKAkSJQodZW5hYmxlZF9ub3RpZmljYXRpb25fY2hhbm5lbHMYBiADKAkSDQoFbW9kZWwYByABKAkiIAoSRGVsZXRlQWdlbnRSZXF1ZXN0EgoKAmlkGAEgASgJIgcKBUVtcHR5IlUKBU1vZGVsEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSFgoOcHJvbXB0X3ByaWNpbmcYAyABKAkSGgoSY29tcGxldGlvbl9wcmljaW5nGAQgASgJIhMKEUxpc3RNb2RlbHNSZXF1ZXN0IjkKEkxpc3RNb2RlbHNSZXNwb25zZRIjCgZtb2RlbHMYASADKAsyEy5ibGlwcHkuYWdlbnQuTW9kZWwywgMKDEFnZW50U2VydmljZRJECgtDcmVhdGVBZ2VudBIgLmJsaXBweS5hZ2VudC5DcmVhdGVBZ2VudFJlcXVlc3QaEy5ibGlwcHkuYWdlbnQuQWdlbnQSPgoIR2V0QWdlbnQSHS5ibGlwcHkuYWdlbnQuR2V0QWdlbnRSZXF1ZXN0GhMuYmxpcHB5LmFnZW50LkFnZW50Ek8KCkxpc3RBZ2VudHMSHy5ibGlwcHkuYWdlbnQuTGlzdEFnZW50c1JlcXVlc3QaIC5ibGlwcHkuYWdlbnQuTGlzdEFnZW50c1Jlc3BvbnNlEkQKC1VwZGF0ZUFnZW50EiAuYmxpcHB5LmFnZW50LlVwZGF0ZUFnZW50UmVxdWVzdBoTLmJsaXBweS5hZ2VudC5BZ2VudBJECgtEZWxldGVBZ2VudBIgLmJsaXBweS5hZ2VudC5EZWxldGVBZ2VudFJlcXVlc3QaEy5ibGlwcHkuYWdlbnQuRW1wdHkSTwoKTGlzdE1vZGVscxIfLmJsaXBweS5hZ2VudC5MaXN0TW9kZWxzUmVxdWVzdBogLmJsaXBweS5hZ2VudC5MaXN0TW9kZWxzUmVzcG9uc2VCK1opZ2l0aHViLmNvbS9kc3RvdGlqbi9ibGlwcHkvaW50ZXJuYWwvYWdlbnRiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message blippy.agent.Agent
 */
export type Agent = Message<"blippy.agent.Agent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string system_prompt = 4;
   */
  systemPrompt: string;

  /**
   * @generated from field: repeated string enabled_tools = 5;
   */
  enabledTools: string[];

  /**
   * Channel IDs
   *
   * @generated from field: repeated string enabled_notification_channels = 6;
   */
  enabledNotificationChannels: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: string model = 9;
   */
  model: string;
};

/**
 * Describes the message blippy.agent.Agent.
 * Use `create(AgentSchema)` to create a new message.
 */
export const AgentSchema: GenMessage<Agent> = /*@__PURE__*/
  messageDesc(file_agent_agent, 0);

/**
 * @generated from message blippy.agent.CreateAgentRequest
 */
export type CreateAgentRequest = Message<"blippy.agent.CreateAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string system_prompt = 3;
   */
  systemPrompt: string;

  /**
   * @generated from field: repeated string enabled_tools = 4;
   */
  enabledTools: string[];

  /**
   * @generated from field: repeated string enabled_notification_channels = 5;
   */
  enabledNotificationChannels: string[];

  /**
   * @generated from field: string model = 6;
   */
  model: string;
};

/**
 * Describes the message blippy.agent.CreateAgentRequest.
 * Use `create(CreateAgentRequestSchema)` to create a new message.
 */
export const CreateAgentRequestSchema: GenMessage<CreateAgentRequest> = /*@__PURE__*/
  messageDesc(file_agent_agent, 1);

/**
 * @generated from message blippy.agent.GetAgentRequest
 */
export type GetAgentRequest = Message<"blippy.agent.GetAgentRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message blippy.agent.GetAgentRequest.
 * Use `create(GetAgentRequestSchema)` to create a new message.
 */
export const GetAgentRequestSchema: GenMessage<GetAgentRequest> = /*@__PURE__*/
  messageDesc(file_agent_agent, 2);

/**
 * @generated from message blippy.agent.ListAgentsRequest
 */
export type ListAgentsRequest = Message<"blippy.agent.ListAgentsRequest"> & {
};

/**
 * Describes the message blippy.agent.ListAgentsRequest.
 * Use `create(ListAgentsRequestSchema)` to create a new message.
 */
export const ListAgentsRequestSchema: GenMessage<ListAgentsRequest> = /*@__PURE__*/
  messageDesc(file_agent_agent, 3);

/**
 * @generated from message blippy.agent.ListAgentsResponse
 */
export type ListAgentsResponse = Message<"blippy.agent.ListAgentsResponse"> & {
  /**
   * @generated from field: repeated blippy.agent.Agent agents = 1;
   */
  agents: Agent[];
};

/**
 * Describes the message blippy.agent.ListAgentsResponse.
 * Use `create(ListAgentsResponseSchema)` to create a new message.
 */
export const ListAgentsResponseSchema: GenMessage<ListAgentsResponse> = /*@__PURE__*/
  messageDesc(file_agent_agent, 4);

/**
 * @generated from message blippy.agent.UpdateAgentRequest
 */
export type UpdateAgentRequest = Message<"blippy.agent.UpdateAgentRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string system_prompt = 4;
   */
  systemPrompt: string;

  /**
   * @generated from field: repeated string enabled_tools = 5;
   */
  enabledTools: string[];

  /**
   * @generated from field: repeated string enabled_notification_channels = 6;
   */
  enabledNotificationChannels: string[];

  /**
   * @generated from field: string model = 7;
   */
  model: string;
};

/**
 * Describes the message blippy.agent.UpdateAgentRequest.
 * Use `create(UpdateAgentRequestSchema)` to create a new message.
 */
export const UpdateAgentRequestSchema: GenMessage<UpdateAgentRequest> = /*@__PURE__*/
  messageDesc(file_agent_agent, 5);

/**
 * @generated from message blippy.agent.DeleteAgentRequest
 */
export type DeleteAgentRequest = Message<"blippy.agent.DeleteAgentRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message blippy.agent.DeleteAgentRequest.
 * Use `create(DeleteAgentRequestSchema)` to create a new message.
 */
export const DeleteAgentRequestSchema: GenMessage<DeleteAgentRequest> = /*@__PURE__*/
  messageDesc(file_agent_agent, 6);

/**
 * @generated from message blippy.agent.Empty
 */
export type Empty = Message<"blippy.agent.Empty"> & {
};

/**
 * Describes the message blippy.agent.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_agent_agent, 7);

/**
 * @generated from message blippy.agent.Model
 */
export type Model = Message<"blippy.agent.Model"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string prompt_pricing = 3;
   */
  promptPricing: string;

  /**
   * @generated from field: string completion_pricing = 4;
   */
  completionPricing: string;
};

/**
 * Describes the message blippy.agent.Model.
 * Use `create(ModelSchema)` to create a new message.
 */
export const ModelSchema: GenMessage<Model> = /*@__PURE__*/
  messageDesc(file_agent_agent, 8);

/**
 * @generated from message blippy.agent.ListModelsRequest
 */
export type ListModelsRequest = Message<"blippy.agent.ListModelsRequest"> & {
};

/**
 * Describes the message blippy.agent.ListModelsRequest.
 * Use `create(ListModelsRequestSchema)` to create a new message.
 */
export const ListModelsRequestSchema: GenMessage<ListModelsRequest> = /*@__PURE__*/
  messageDesc(file_agent_agent, 9);

/**
 * @generated from message blippy.agent.ListModelsResponse
 */
export type ListModelsResponse = Message<"blippy.agent.ListModelsResponse"> & {
  /**
   * @generated from field: repeated blippy.agent.Model models = 1;
   */
  models: Model[];
};

/**
 * Describes the message blippy.agent.ListModelsResponse.
 * Use `create(ListModelsResponseSchema)` to create a new message.
 */
export const ListModelsResponseSchema: GenMessage<ListModelsResponse> = /*@__PURE__*/
  messageDesc(file_agent_agent, 10);

/**
 * @generated from service blippy.agent.AgentService
 */
export const AgentService: GenService<{
  /**
   * @generated from rpc blippy.agent.AgentService.CreateAgent
   */
  createAgent: {
    methodKind: "unary";
    input: typeof CreateAgentRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * @generated from rpc blippy.agent.AgentService.GetAgent
   */
  getAgent: {
    methodKind: "unary";
    input: typeof GetAgentRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * @generated from rpc blippy.agent.AgentService.ListAgents
   */
  listAgents: {
    methodKind: "unary";
    input: typeof ListAgentsRequestSchema;
    output: typeof ListAgentsResponseSchema;
  },
  /**
   * @generated from rpc blippy.agent.AgentService.UpdateAgent
   */
  updateAgent: {
    methodKind: "unary";
    input: typeof UpdateAgentRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * @generated from rpc blippy.agent.AgentService.DeleteAgent
   */
  deleteAgent: {
    methodKind: "unary";
    input: typeof DeleteAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc blippy.agent.AgentService.ListModels
   */
  listModels: {
    methodKind: "unary";
    input: typeof ListModelsRequestSchema;
    output: typeof ListModelsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_agent_agent, 0);

