// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file agent/agent.proto (package blippy.agent, syntax proto3)
/* eslint-disable */

import { AgentService } from "./agent_pb";

/**
 * @generated from rpc blippy.agent.AgentService.CreateAgent
 */
export const createAgent = AgentService.method.createAgent;

/**
 * @generated from rpc blippy.agent.AgentService.GetAgent
 */
export const getAgent = AgentService.method.getAgent;

/**
 * @generated from rpc blippy.agent.AgentService.ListAgents
 */
export const listAgents = AgentService.method.listAgents;

/**
 * @generated from rpc blippy.agent.AgentService.UpdateAgent
 */
export const updateAgent = AgentService.method.updateAgent;

/**
 * @generated from rpc blippy.agent.AgentService.DeleteAgent
 */
export const deleteAgent = AgentService.method.deleteAgent;

/**
 * @generated from rpc blippy.agent.AgentService.ListModels
 */
export const listModels = AgentService.method.listModels;
