// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trigger/trigger.proto

package trigger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"` // optional, empty if not set
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"` // optional, zero value if not set
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_trigger_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *Trigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trigger) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Trigger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trigger) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Trigger) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *Trigger) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Trigger) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *Trigger) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Trigger) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CronExpr      string                 `protobuf:"bytes,4,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"` // optional, for scheduled triggers
	Delay         string                 `protobuf:"bytes,5,opt,name=delay,proto3" json:"delay,omitempty"`                       // optional, for one-time delayed triggers (e.g., "5m", "1h")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTriggerRequest) Reset() {
	*x = CreateTriggerRequest{}
	mi := &file_trigger_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTriggerRequest) ProtoMessage() {}

func (x *CreateTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTriggerRequest.ProtoReflect.Descriptor instead.
func (*CreateTriggerRequest) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTriggerRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateTriggerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTriggerRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTriggerRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CreateTriggerRequest) GetDelay() string {
	if x != nil {
		return x.Delay
	}
	return ""
}

type GetTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTriggerRequest) Reset() {
	*x = GetTriggerRequest{}
	mi := &file_trigger_trigger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTriggerRequest) ProtoMessage() {}

func (x *GetTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTriggerRequest.ProtoReflect.Descriptor instead.
func (*GetTriggerRequest) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{2}
}

func (x *GetTriggerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTriggersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTriggersRequest) Reset() {
	*x = ListTriggersRequest{}
	mi := &file_trigger_trigger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTriggersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTriggersRequest) ProtoMessage() {}

func (x *ListTriggersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTriggersRequest.ProtoReflect.Descriptor instead.
func (*ListTriggersRequest) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{3}
}

func (x *ListTriggersRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListTriggersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggers      []*Trigger             `protobuf:"bytes,1,rep,name=triggers,proto3" json:"triggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTriggersResponse) Reset() {
	*x = ListTriggersResponse{}
	mi := &file_trigger_trigger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTriggersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTriggersResponse) ProtoMessage() {}

func (x *ListTriggersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTriggersResponse.ProtoReflect.Descriptor instead.
func (*ListTriggersResponse) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{4}
}

func (x *ListTriggersResponse) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

type UpdateTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CronExpr      string                 `protobuf:"bytes,4,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTriggerRequest) Reset() {
	*x = UpdateTriggerRequest{}
	mi := &file_trigger_trigger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTriggerRequest) ProtoMessage() {}

func (x *UpdateTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTriggerRequest.ProtoReflect.Descriptor instead.
func (*UpdateTriggerRequest) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTriggerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTriggerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTriggerRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpdateTriggerRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *UpdateTriggerRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DeleteTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTriggerRequest) Reset() {
	*x = DeleteTriggerRequest{}
	mi := &file_trigger_trigger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTriggerRequest) ProtoMessage() {}

func (x *DeleteTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTriggerRequest.ProtoReflect.Descriptor instead.
func (*DeleteTriggerRequest) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTriggerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_trigger_trigger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_trigger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_trigger_trigger_proto_rawDescGZIP(), []int{7}
}

var File_trigger_trigger_proto protoreflect.FileDescriptor

const file_trigger_trigger_proto_rawDesc = "" +
	"\n" +
	"\x15trigger/trigger.proto\x12\x0eblippy.trigger\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x02\n" +
	"\aTrigger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12:\n" +
	"\vnext_run_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x01\n" +
	"\x14CreateTriggerRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tcron_expr\x18\x04 \x01(\tR\bcronExpr\x12\x14\n" +
	"\x05delay\x18\x05 \x01(\tR\x05delay\"#\n" +
	"\x11GetTriggerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x13ListTriggersRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"K\n" +
	"\x14ListTriggersResponse\x123\n" +
	"\btriggers\x18\x01 \x03(\v2\x17.blippy.trigger.TriggerR\btriggers\"\x89\x01\n" +
	"\x14UpdateTriggerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tcron_expr\x18\x04 \x01(\tR\bcronExpr\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"&\n" +
	"\x14DeleteTriggerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\xa3\x03\n" +
	"\x0eTriggerService\x12N\n" +
	"\rCreateTrigger\x12$.blippy.trigger.CreateTriggerRequest\x1a\x17.blippy.trigger.Trigger\x12H\n" +
	"\n" +
	"GetTrigger\x12!.blippy.trigger.GetTriggerRequest\x1a\x17.blippy.trigger.Trigger\x12Y\n" +
	"\fListTriggers\x12#.blippy.trigger.ListTriggersRequest\x1a$.blippy.trigger.ListTriggersResponse\x12N\n" +
	"\rUpdateTrigger\x12$.blippy.trigger.UpdateTriggerRequest\x1a\x17.blippy.trigger.Trigger\x12L\n" +
	"\rDeleteTrigger\x12$.blippy.trigger.DeleteTriggerRequest\x1a\x15.blippy.trigger.EmptyB-Z+github.com/dstotijn/blippy/internal/triggerb\x06proto3"

var (
	file_trigger_trigger_proto_rawDescOnce sync.Once
	file_trigger_trigger_proto_rawDescData []byte
)

func file_trigger_trigger_proto_rawDescGZIP() []byte {
	file_trigger_trigger_proto_rawDescOnce.Do(func() {
		file_trigger_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trigger_trigger_proto_rawDesc), len(file_trigger_trigger_proto_rawDesc)))
	})
	return file_trigger_trigger_proto_rawDescData
}

var file_trigger_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_trigger_trigger_proto_goTypes = []any{
	(*Trigger)(nil),               // 0: blippy.trigger.Trigger
	(*CreateTriggerRequest)(nil),  // 1: blippy.trigger.CreateTriggerRequest
	(*GetTriggerRequest)(nil),     // 2: blippy.trigger.GetTriggerRequest
	(*ListTriggersRequest)(nil),   // 3: blippy.trigger.ListTriggersRequest
	(*ListTriggersResponse)(nil),  // 4: blippy.trigger.ListTriggersResponse
	(*UpdateTriggerRequest)(nil),  // 5: blippy.trigger.UpdateTriggerRequest
	(*DeleteTriggerRequest)(nil),  // 6: blippy.trigger.DeleteTriggerRequest
	(*Empty)(nil),                 // 7: blippy.trigger.Empty
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_trigger_trigger_proto_depIdxs = []int32{
	8, // 0: blippy.trigger.Trigger.next_run_at:type_name -> google.protobuf.Timestamp
	8, // 1: blippy.trigger.Trigger.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: blippy.trigger.Trigger.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: blippy.trigger.ListTriggersResponse.triggers:type_name -> blippy.trigger.Trigger
	1, // 4: blippy.trigger.TriggerService.CreateTrigger:input_type -> blippy.trigger.CreateTriggerRequest
	2, // 5: blippy.trigger.TriggerService.GetTrigger:input_type -> blippy.trigger.GetTriggerRequest
	3, // 6: blippy.trigger.TriggerService.ListTriggers:input_type -> blippy.trigger.ListTriggersRequest
	5, // 7: blippy.trigger.TriggerService.UpdateTrigger:input_type -> blippy.trigger.UpdateTriggerRequest
	6, // 8: blippy.trigger.TriggerService.DeleteTrigger:input_type -> blippy.trigger.DeleteTriggerRequest
	0, // 9: blippy.trigger.TriggerService.CreateTrigger:output_type -> blippy.trigger.Trigger
	0, // 10: blippy.trigger.TriggerService.GetTrigger:output_type -> blippy.trigger.Trigger
	4, // 11: blippy.trigger.TriggerService.ListTriggers:output_type -> blippy.trigger.ListTriggersResponse
	0, // 12: blippy.trigger.TriggerService.UpdateTrigger:output_type -> blippy.trigger.Trigger
	7, // 13: blippy.trigger.TriggerService.DeleteTrigger:output_type -> blippy.trigger.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_trigger_trigger_proto_init() }
func file_trigger_trigger_proto_init() {
	if File_trigger_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trigger_trigger_proto_rawDesc), len(file_trigger_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trigger_trigger_proto_goTypes,
		DependencyIndexes: file_trigger_trigger_proto_depIdxs,
		MessageInfos:      file_trigger_trigger_proto_msgTypes,
	}.Build()
	File_trigger_trigger_proto = out.File
	file_trigger_trigger_proto_goTypes = nil
	file_trigger_trigger_proto_depIdxs = nil
}
