// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: trigger/trigger.proto

package trigger

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TriggerServiceName is the fully-qualified name of the TriggerService service.
	TriggerServiceName = "blippy.trigger.TriggerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TriggerServiceCreateTriggerProcedure is the fully-qualified name of the TriggerService's
	// CreateTrigger RPC.
	TriggerServiceCreateTriggerProcedure = "/blippy.trigger.TriggerService/CreateTrigger"
	// TriggerServiceGetTriggerProcedure is the fully-qualified name of the TriggerService's GetTrigger
	// RPC.
	TriggerServiceGetTriggerProcedure = "/blippy.trigger.TriggerService/GetTrigger"
	// TriggerServiceListTriggersProcedure is the fully-qualified name of the TriggerService's
	// ListTriggers RPC.
	TriggerServiceListTriggersProcedure = "/blippy.trigger.TriggerService/ListTriggers"
	// TriggerServiceUpdateTriggerProcedure is the fully-qualified name of the TriggerService's
	// UpdateTrigger RPC.
	TriggerServiceUpdateTriggerProcedure = "/blippy.trigger.TriggerService/UpdateTrigger"
	// TriggerServiceDeleteTriggerProcedure is the fully-qualified name of the TriggerService's
	// DeleteTrigger RPC.
	TriggerServiceDeleteTriggerProcedure = "/blippy.trigger.TriggerService/DeleteTrigger"
)

// TriggerServiceClient is a client for the blippy.trigger.TriggerService service.
type TriggerServiceClient interface {
	CreateTrigger(context.Context, *connect.Request[CreateTriggerRequest]) (*connect.Response[Trigger], error)
	GetTrigger(context.Context, *connect.Request[GetTriggerRequest]) (*connect.Response[Trigger], error)
	ListTriggers(context.Context, *connect.Request[ListTriggersRequest]) (*connect.Response[ListTriggersResponse], error)
	UpdateTrigger(context.Context, *connect.Request[UpdateTriggerRequest]) (*connect.Response[Trigger], error)
	DeleteTrigger(context.Context, *connect.Request[DeleteTriggerRequest]) (*connect.Response[Empty], error)
}

// NewTriggerServiceClient constructs a client for the blippy.trigger.TriggerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTriggerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TriggerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	triggerServiceMethods := File_trigger_trigger_proto.Services().ByName("TriggerService").Methods()
	return &triggerServiceClient{
		createTrigger: connect.NewClient[CreateTriggerRequest, Trigger](
			httpClient,
			baseURL+TriggerServiceCreateTriggerProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("CreateTrigger")),
			connect.WithClientOptions(opts...),
		),
		getTrigger: connect.NewClient[GetTriggerRequest, Trigger](
			httpClient,
			baseURL+TriggerServiceGetTriggerProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("GetTrigger")),
			connect.WithClientOptions(opts...),
		),
		listTriggers: connect.NewClient[ListTriggersRequest, ListTriggersResponse](
			httpClient,
			baseURL+TriggerServiceListTriggersProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("ListTriggers")),
			connect.WithClientOptions(opts...),
		),
		updateTrigger: connect.NewClient[UpdateTriggerRequest, Trigger](
			httpClient,
			baseURL+TriggerServiceUpdateTriggerProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("UpdateTrigger")),
			connect.WithClientOptions(opts...),
		),
		deleteTrigger: connect.NewClient[DeleteTriggerRequest, Empty](
			httpClient,
			baseURL+TriggerServiceDeleteTriggerProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("DeleteTrigger")),
			connect.WithClientOptions(opts...),
		),
	}
}

// triggerServiceClient implements TriggerServiceClient.
type triggerServiceClient struct {
	createTrigger *connect.Client[CreateTriggerRequest, Trigger]
	getTrigger    *connect.Client[GetTriggerRequest, Trigger]
	listTriggers  *connect.Client[ListTriggersRequest, ListTriggersResponse]
	updateTrigger *connect.Client[UpdateTriggerRequest, Trigger]
	deleteTrigger *connect.Client[DeleteTriggerRequest, Empty]
}

// CreateTrigger calls blippy.trigger.TriggerService.CreateTrigger.
func (c *triggerServiceClient) CreateTrigger(ctx context.Context, req *connect.Request[CreateTriggerRequest]) (*connect.Response[Trigger], error) {
	return c.createTrigger.CallUnary(ctx, req)
}

// GetTrigger calls blippy.trigger.TriggerService.GetTrigger.
func (c *triggerServiceClient) GetTrigger(ctx context.Context, req *connect.Request[GetTriggerRequest]) (*connect.Response[Trigger], error) {
	return c.getTrigger.CallUnary(ctx, req)
}

// ListTriggers calls blippy.trigger.TriggerService.ListTriggers.
func (c *triggerServiceClient) ListTriggers(ctx context.Context, req *connect.Request[ListTriggersRequest]) (*connect.Response[ListTriggersResponse], error) {
	return c.listTriggers.CallUnary(ctx, req)
}

// UpdateTrigger calls blippy.trigger.TriggerService.UpdateTrigger.
func (c *triggerServiceClient) UpdateTrigger(ctx context.Context, req *connect.Request[UpdateTriggerRequest]) (*connect.Response[Trigger], error) {
	return c.updateTrigger.CallUnary(ctx, req)
}

// DeleteTrigger calls blippy.trigger.TriggerService.DeleteTrigger.
func (c *triggerServiceClient) DeleteTrigger(ctx context.Context, req *connect.Request[DeleteTriggerRequest]) (*connect.Response[Empty], error) {
	return c.deleteTrigger.CallUnary(ctx, req)
}

// TriggerServiceHandler is an implementation of the blippy.trigger.TriggerService service.
type TriggerServiceHandler interface {
	CreateTrigger(context.Context, *connect.Request[CreateTriggerRequest]) (*connect.Response[Trigger], error)
	GetTrigger(context.Context, *connect.Request[GetTriggerRequest]) (*connect.Response[Trigger], error)
	ListTriggers(context.Context, *connect.Request[ListTriggersRequest]) (*connect.Response[ListTriggersResponse], error)
	UpdateTrigger(context.Context, *connect.Request[UpdateTriggerRequest]) (*connect.Response[Trigger], error)
	DeleteTrigger(context.Context, *connect.Request[DeleteTriggerRequest]) (*connect.Response[Empty], error)
}

// NewTriggerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTriggerServiceHandler(svc TriggerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	triggerServiceMethods := File_trigger_trigger_proto.Services().ByName("TriggerService").Methods()
	triggerServiceCreateTriggerHandler := connect.NewUnaryHandler(
		TriggerServiceCreateTriggerProcedure,
		svc.CreateTrigger,
		connect.WithSchema(triggerServiceMethods.ByName("CreateTrigger")),
		connect.WithHandlerOptions(opts...),
	)
	triggerServiceGetTriggerHandler := connect.NewUnaryHandler(
		TriggerServiceGetTriggerProcedure,
		svc.GetTrigger,
		connect.WithSchema(triggerServiceMethods.ByName("GetTrigger")),
		connect.WithHandlerOptions(opts...),
	)
	triggerServiceListTriggersHandler := connect.NewUnaryHandler(
		TriggerServiceListTriggersProcedure,
		svc.ListTriggers,
		connect.WithSchema(triggerServiceMethods.ByName("ListTriggers")),
		connect.WithHandlerOptions(opts...),
	)
	triggerServiceUpdateTriggerHandler := connect.NewUnaryHandler(
		TriggerServiceUpdateTriggerProcedure,
		svc.UpdateTrigger,
		connect.WithSchema(triggerServiceMethods.ByName("UpdateTrigger")),
		connect.WithHandlerOptions(opts...),
	)
	triggerServiceDeleteTriggerHandler := connect.NewUnaryHandler(
		TriggerServiceDeleteTriggerProcedure,
		svc.DeleteTrigger,
		connect.WithSchema(triggerServiceMethods.ByName("DeleteTrigger")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blippy.trigger.TriggerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TriggerServiceCreateTriggerProcedure:
			triggerServiceCreateTriggerHandler.ServeHTTP(w, r)
		case TriggerServiceGetTriggerProcedure:
			triggerServiceGetTriggerHandler.ServeHTTP(w, r)
		case TriggerServiceListTriggersProcedure:
			triggerServiceListTriggersHandler.ServeHTTP(w, r)
		case TriggerServiceUpdateTriggerProcedure:
			triggerServiceUpdateTriggerHandler.ServeHTTP(w, r)
		case TriggerServiceDeleteTriggerProcedure:
			triggerServiceDeleteTriggerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTriggerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTriggerServiceHandler struct{}

func (UnimplementedTriggerServiceHandler) CreateTrigger(context.Context, *connect.Request[CreateTriggerRequest]) (*connect.Response[Trigger], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.trigger.TriggerService.CreateTrigger is not implemented"))
}

func (UnimplementedTriggerServiceHandler) GetTrigger(context.Context, *connect.Request[GetTriggerRequest]) (*connect.Response[Trigger], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.trigger.TriggerService.GetTrigger is not implemented"))
}

func (UnimplementedTriggerServiceHandler) ListTriggers(context.Context, *connect.Request[ListTriggersRequest]) (*connect.Response[ListTriggersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.trigger.TriggerService.ListTriggers is not implemented"))
}

func (UnimplementedTriggerServiceHandler) UpdateTrigger(context.Context, *connect.Request[UpdateTriggerRequest]) (*connect.Response[Trigger], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.trigger.TriggerService.UpdateTrigger is not implemented"))
}

func (UnimplementedTriggerServiceHandler) DeleteTrigger(context.Context, *connect.Request[DeleteTriggerRequest]) (*connect.Response[Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.trigger.TriggerService.DeleteTrigger is not implemented"))
}
