// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentFilesystemRoot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	EnabledTools  []string               `protobuf:"bytes,2,rep,name=enabled_tools,json=enabledTools,proto3" json:"enabled_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFilesystemRoot) Reset() {
	*x = AgentFilesystemRoot{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFilesystemRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFilesystemRoot) ProtoMessage() {}

func (x *AgentFilesystemRoot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFilesystemRoot.ProtoReflect.Descriptor instead.
func (*AgentFilesystemRoot) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentFilesystemRoot) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *AgentFilesystemRoot) GetEnabledTools() []string {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

type Agent struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                 string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt                string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	EnabledTools                []string               `protobuf:"bytes,5,rep,name=enabled_tools,json=enabledTools,proto3" json:"enabled_tools,omitempty"`
	EnabledNotificationChannels []string               `protobuf:"bytes,6,rep,name=enabled_notification_channels,json=enabledNotificationChannels,proto3" json:"enabled_notification_channels,omitempty"` // Channel IDs
	CreatedAt                   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Model                       string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	EnabledFilesystemRoots      []*AgentFilesystemRoot `protobuf:"bytes,10,rep,name=enabled_filesystem_roots,json=enabledFilesystemRoots,proto3" json:"enabled_filesystem_roots,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Agent) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Agent) GetEnabledTools() []string {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

func (x *Agent) GetEnabledNotificationChannels() []string {
	if x != nil {
		return x.EnabledNotificationChannels
	}
	return nil
}

func (x *Agent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Agent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetEnabledFilesystemRoots() []*AgentFilesystemRoot {
	if x != nil {
		return x.EnabledFilesystemRoots
	}
	return nil
}

type CreateAgentRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Name                        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description                 string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt                string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	EnabledTools                []string               `protobuf:"bytes,4,rep,name=enabled_tools,json=enabledTools,proto3" json:"enabled_tools,omitempty"`
	EnabledNotificationChannels []string               `protobuf:"bytes,5,rep,name=enabled_notification_channels,json=enabledNotificationChannels,proto3" json:"enabled_notification_channels,omitempty"`
	Model                       string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	EnabledFilesystemRoots      []*AgentFilesystemRoot `protobuf:"bytes,7,rep,name=enabled_filesystem_roots,json=enabledFilesystemRoots,proto3" json:"enabled_filesystem_roots,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreateAgentRequest) GetEnabledTools() []string {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

func (x *CreateAgentRequest) GetEnabledNotificationChannels() []string {
	if x != nil {
		return x.EnabledNotificationChannels
	}
	return nil
}

func (x *CreateAgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateAgentRequest) GetEnabledFilesystemRoots() []*AgentFilesystemRoot {
	if x != nil {
		return x.EnabledFilesystemRoots
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type UpdateAgentRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                 string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt                string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	EnabledTools                []string               `protobuf:"bytes,5,rep,name=enabled_tools,json=enabledTools,proto3" json:"enabled_tools,omitempty"`
	EnabledNotificationChannels []string               `protobuf:"bytes,6,rep,name=enabled_notification_channels,json=enabledNotificationChannels,proto3" json:"enabled_notification_channels,omitempty"`
	Model                       string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	EnabledFilesystemRoots      []*AgentFilesystemRoot `protobuf:"bytes,8,rep,name=enabled_filesystem_roots,json=enabledFilesystemRoots,proto3" json:"enabled_filesystem_roots,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdateAgentRequest) GetEnabledTools() []string {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

func (x *UpdateAgentRequest) GetEnabledNotificationChannels() []string {
	if x != nil {
		return x.EnabledNotificationChannels
	}
	return nil
}

func (x *UpdateAgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateAgentRequest) GetEnabledFilesystemRoots() []*AgentFilesystemRoot {
	if x != nil {
		return x.EnabledFilesystemRoots
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{8}
}

type Model struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PromptPricing     string                 `protobuf:"bytes,3,opt,name=prompt_pricing,json=promptPricing,proto3" json:"prompt_pricing,omitempty"`
	CompletionPricing string                 `protobuf:"bytes,4,opt,name=completion_pricing,json=completionPricing,proto3" json:"completion_pricing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetPromptPricing() string {
	if x != nil {
		return x.PromptPricing
	}
	return ""
}

func (x *Model) GetCompletionPricing() string {
	if x != nil {
		return x.CompletionPricing
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{10}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\fblippy.agent\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x13AgentFilesystemRoot\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12#\n" +
	"\renabled_tools\x18\x02 \x03(\tR\fenabledTools\"\xc4\x03\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12#\n" +
	"\renabled_tools\x18\x05 \x03(\tR\fenabledTools\x12B\n" +
	"\x1denabled_notification_channels\x18\x06 \x03(\tR\x1benabledNotificationChannels\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12[\n" +
	"\x18enabled_filesystem_roots\x18\n" +
	" \x03(\v2!.blippy.agent.AgentFilesystemRootR\x16enabledFilesystemRoots\"\xcb\x02\n" +
	"\x12CreateAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12#\n" +
	"\renabled_tools\x18\x04 \x03(\tR\fenabledTools\x12B\n" +
	"\x1denabled_notification_channels\x18\x05 \x03(\tR\x1benabledNotificationChannels\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12[\n" +
	"\x18enabled_filesystem_roots\x18\a \x03(\v2!.blippy.agent.AgentFilesystemRootR\x16enabledFilesystemRoots\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11ListAgentsRequest\"A\n" +
	"\x12ListAgentsResponse\x12+\n" +
	"\x06agents\x18\x01 \x03(\v2\x13.blippy.agent.AgentR\x06agents\"\xdb\x02\n" +
	"\x12UpdateAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12#\n" +
	"\renabled_tools\x18\x05 \x03(\tR\fenabledTools\x12B\n" +
	"\x1denabled_notification_channels\x18\x06 \x03(\tR\x1benabledNotificationChannels\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12[\n" +
	"\x18enabled_filesystem_roots\x18\b \x03(\v2!.blippy.agent.AgentFilesystemRootR\x16enabledFilesystemRoots\"$\n" +
	"\x12DeleteAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty\"\x81\x01\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eprompt_pricing\x18\x03 \x01(\tR\rpromptPricing\x12-\n" +
	"\x12completion_pricing\x18\x04 \x01(\tR\x11completionPricing\"\x13\n" +
	"\x11ListModelsRequest\"A\n" +
	"\x12ListModelsResponse\x12+\n" +
	"\x06models\x18\x01 \x03(\v2\x13.blippy.agent.ModelR\x06models2\xc2\x03\n" +
	"\fAgentService\x12D\n" +
	"\vCreateAgent\x12 .blippy.agent.CreateAgentRequest\x1a\x13.blippy.agent.Agent\x12>\n" +
	"\bGetAgent\x12\x1d.blippy.agent.GetAgentRequest\x1a\x13.blippy.agent.Agent\x12O\n" +
	"\n" +
	"ListAgents\x12\x1f.blippy.agent.ListAgentsRequest\x1a .blippy.agent.ListAgentsResponse\x12D\n" +
	"\vUpdateAgent\x12 .blippy.agent.UpdateAgentRequest\x1a\x13.blippy.agent.Agent\x12D\n" +
	"\vDeleteAgent\x12 .blippy.agent.DeleteAgentRequest\x1a\x13.blippy.agent.Empty\x12O\n" +
	"\n" +
	"ListModels\x12\x1f.blippy.agent.ListModelsRequest\x1a .blippy.agent.ListModelsResponseB+Z)github.com/dstotijn/blippy/internal/agentb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_agent_proto_goTypes = []any{
	(*AgentFilesystemRoot)(nil),   // 0: blippy.agent.AgentFilesystemRoot
	(*Agent)(nil),                 // 1: blippy.agent.Agent
	(*CreateAgentRequest)(nil),    // 2: blippy.agent.CreateAgentRequest
	(*GetAgentRequest)(nil),       // 3: blippy.agent.GetAgentRequest
	(*ListAgentsRequest)(nil),     // 4: blippy.agent.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 5: blippy.agent.ListAgentsResponse
	(*UpdateAgentRequest)(nil),    // 6: blippy.agent.UpdateAgentRequest
	(*DeleteAgentRequest)(nil),    // 7: blippy.agent.DeleteAgentRequest
	(*Empty)(nil),                 // 8: blippy.agent.Empty
	(*Model)(nil),                 // 9: blippy.agent.Model
	(*ListModelsRequest)(nil),     // 10: blippy.agent.ListModelsRequest
	(*ListModelsResponse)(nil),    // 11: blippy.agent.ListModelsResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_agent_agent_proto_depIdxs = []int32{
	12, // 0: blippy.agent.Agent.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: blippy.agent.Agent.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: blippy.agent.Agent.enabled_filesystem_roots:type_name -> blippy.agent.AgentFilesystemRoot
	0,  // 3: blippy.agent.CreateAgentRequest.enabled_filesystem_roots:type_name -> blippy.agent.AgentFilesystemRoot
	1,  // 4: blippy.agent.ListAgentsResponse.agents:type_name -> blippy.agent.Agent
	0,  // 5: blippy.agent.UpdateAgentRequest.enabled_filesystem_roots:type_name -> blippy.agent.AgentFilesystemRoot
	9,  // 6: blippy.agent.ListModelsResponse.models:type_name -> blippy.agent.Model
	2,  // 7: blippy.agent.AgentService.CreateAgent:input_type -> blippy.agent.CreateAgentRequest
	3,  // 8: blippy.agent.AgentService.GetAgent:input_type -> blippy.agent.GetAgentRequest
	4,  // 9: blippy.agent.AgentService.ListAgents:input_type -> blippy.agent.ListAgentsRequest
	6,  // 10: blippy.agent.AgentService.UpdateAgent:input_type -> blippy.agent.UpdateAgentRequest
	7,  // 11: blippy.agent.AgentService.DeleteAgent:input_type -> blippy.agent.DeleteAgentRequest
	10, // 12: blippy.agent.AgentService.ListModels:input_type -> blippy.agent.ListModelsRequest
	1,  // 13: blippy.agent.AgentService.CreateAgent:output_type -> blippy.agent.Agent
	1,  // 14: blippy.agent.AgentService.GetAgent:output_type -> blippy.agent.Agent
	5,  // 15: blippy.agent.AgentService.ListAgents:output_type -> blippy.agent.ListAgentsResponse
	1,  // 16: blippy.agent.AgentService.UpdateAgent:output_type -> blippy.agent.Agent
	8,  // 17: blippy.agent.AgentService.DeleteAgent:output_type -> blippy.agent.Empty
	11, // 18: blippy.agent.AgentService.ListModels:output_type -> blippy.agent.ListModelsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
