// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent/agent.proto

package agent

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "blippy.agent.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceCreateAgentProcedure is the fully-qualified name of the AgentService's CreateAgent
	// RPC.
	AgentServiceCreateAgentProcedure = "/blippy.agent.AgentService/CreateAgent"
	// AgentServiceGetAgentProcedure is the fully-qualified name of the AgentService's GetAgent RPC.
	AgentServiceGetAgentProcedure = "/blippy.agent.AgentService/GetAgent"
	// AgentServiceListAgentsProcedure is the fully-qualified name of the AgentService's ListAgents RPC.
	AgentServiceListAgentsProcedure = "/blippy.agent.AgentService/ListAgents"
	// AgentServiceUpdateAgentProcedure is the fully-qualified name of the AgentService's UpdateAgent
	// RPC.
	AgentServiceUpdateAgentProcedure = "/blippy.agent.AgentService/UpdateAgent"
	// AgentServiceDeleteAgentProcedure is the fully-qualified name of the AgentService's DeleteAgent
	// RPC.
	AgentServiceDeleteAgentProcedure = "/blippy.agent.AgentService/DeleteAgent"
)

// AgentServiceClient is a client for the blippy.agent.AgentService service.
type AgentServiceClient interface {
	CreateAgent(context.Context, *connect.Request[CreateAgentRequest]) (*connect.Response[Agent], error)
	GetAgent(context.Context, *connect.Request[GetAgentRequest]) (*connect.Response[Agent], error)
	ListAgents(context.Context, *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error)
	UpdateAgent(context.Context, *connect.Request[UpdateAgentRequest]) (*connect.Response[Agent], error)
	DeleteAgent(context.Context, *connect.Request[DeleteAgentRequest]) (*connect.Response[Empty], error)
}

// NewAgentServiceClient constructs a client for the blippy.agent.AgentService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := File_agent_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		createAgent: connect.NewClient[CreateAgentRequest, Agent](
			httpClient,
			baseURL+AgentServiceCreateAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[GetAgentRequest, Agent](
			httpClient,
			baseURL+AgentServiceGetAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[ListAgentsRequest, ListAgentsResponse](
			httpClient,
			baseURL+AgentServiceListAgentsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[UpdateAgentRequest, Agent](
			httpClient,
			baseURL+AgentServiceUpdateAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[DeleteAgentRequest, Empty](
			httpClient,
			baseURL+AgentServiceDeleteAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteAgent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	createAgent *connect.Client[CreateAgentRequest, Agent]
	getAgent    *connect.Client[GetAgentRequest, Agent]
	listAgents  *connect.Client[ListAgentsRequest, ListAgentsResponse]
	updateAgent *connect.Client[UpdateAgentRequest, Agent]
	deleteAgent *connect.Client[DeleteAgentRequest, Empty]
}

// CreateAgent calls blippy.agent.AgentService.CreateAgent.
func (c *agentServiceClient) CreateAgent(ctx context.Context, req *connect.Request[CreateAgentRequest]) (*connect.Response[Agent], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// GetAgent calls blippy.agent.AgentService.GetAgent.
func (c *agentServiceClient) GetAgent(ctx context.Context, req *connect.Request[GetAgentRequest]) (*connect.Response[Agent], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// ListAgents calls blippy.agent.AgentService.ListAgents.
func (c *agentServiceClient) ListAgents(ctx context.Context, req *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// UpdateAgent calls blippy.agent.AgentService.UpdateAgent.
func (c *agentServiceClient) UpdateAgent(ctx context.Context, req *connect.Request[UpdateAgentRequest]) (*connect.Response[Agent], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

// DeleteAgent calls blippy.agent.AgentService.DeleteAgent.
func (c *agentServiceClient) DeleteAgent(ctx context.Context, req *connect.Request[DeleteAgentRequest]) (*connect.Response[Empty], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the blippy.agent.AgentService service.
type AgentServiceHandler interface {
	CreateAgent(context.Context, *connect.Request[CreateAgentRequest]) (*connect.Response[Agent], error)
	GetAgent(context.Context, *connect.Request[GetAgentRequest]) (*connect.Response[Agent], error)
	ListAgents(context.Context, *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error)
	UpdateAgent(context.Context, *connect.Request[UpdateAgentRequest]) (*connect.Response[Agent], error)
	DeleteAgent(context.Context, *connect.Request[DeleteAgentRequest]) (*connect.Response[Empty], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := File_agent_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceCreateAgentHandler := connect.NewUnaryHandler(
		AgentServiceCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(agentServiceMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAgentHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListAgentsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateAgentHandler := connect.NewUnaryHandler(
		AgentServiceUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(agentServiceMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteAgentHandler := connect.NewUnaryHandler(
		AgentServiceDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(agentServiceMethods.ByName("DeleteAgent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blippy.agent.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceCreateAgentProcedure:
			agentServiceCreateAgentHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentProcedure:
			agentServiceGetAgentHandler.ServeHTTP(w, r)
		case AgentServiceListAgentsProcedure:
			agentServiceListAgentsHandler.ServeHTTP(w, r)
		case AgentServiceUpdateAgentProcedure:
			agentServiceUpdateAgentHandler.ServeHTTP(w, r)
		case AgentServiceDeleteAgentProcedure:
			agentServiceDeleteAgentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) CreateAgent(context.Context, *connect.Request[CreateAgentRequest]) (*connect.Response[Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.agent.AgentService.CreateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgent(context.Context, *connect.Request[GetAgentRequest]) (*connect.Response[Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.agent.AgentService.GetAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListAgents(context.Context, *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.agent.AgentService.ListAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateAgent(context.Context, *connect.Request[UpdateAgentRequest]) (*connect.Response[Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.agent.AgentService.UpdateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteAgent(context.Context, *connect.Request[DeleteAgentRequest]) (*connect.Response[Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.agent.AgentService.DeleteAgent is not implemented"))
}
