// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: notification/notification.proto

package notification

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationChannelServiceName is the fully-qualified name of the NotificationChannelService
	// service.
	NotificationChannelServiceName = "blippy.notification.NotificationChannelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationChannelServiceCreateNotificationChannelProcedure is the fully-qualified name of the
	// NotificationChannelService's CreateNotificationChannel RPC.
	NotificationChannelServiceCreateNotificationChannelProcedure = "/blippy.notification.NotificationChannelService/CreateNotificationChannel"
	// NotificationChannelServiceGetNotificationChannelProcedure is the fully-qualified name of the
	// NotificationChannelService's GetNotificationChannel RPC.
	NotificationChannelServiceGetNotificationChannelProcedure = "/blippy.notification.NotificationChannelService/GetNotificationChannel"
	// NotificationChannelServiceListNotificationChannelsProcedure is the fully-qualified name of the
	// NotificationChannelService's ListNotificationChannels RPC.
	NotificationChannelServiceListNotificationChannelsProcedure = "/blippy.notification.NotificationChannelService/ListNotificationChannels"
	// NotificationChannelServiceUpdateNotificationChannelProcedure is the fully-qualified name of the
	// NotificationChannelService's UpdateNotificationChannel RPC.
	NotificationChannelServiceUpdateNotificationChannelProcedure = "/blippy.notification.NotificationChannelService/UpdateNotificationChannel"
	// NotificationChannelServiceDeleteNotificationChannelProcedure is the fully-qualified name of the
	// NotificationChannelService's DeleteNotificationChannel RPC.
	NotificationChannelServiceDeleteNotificationChannelProcedure = "/blippy.notification.NotificationChannelService/DeleteNotificationChannel"
)

// NotificationChannelServiceClient is a client for the
// blippy.notification.NotificationChannelService service.
type NotificationChannelServiceClient interface {
	CreateNotificationChannel(context.Context, *connect.Request[CreateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error)
	GetNotificationChannel(context.Context, *connect.Request[GetNotificationChannelRequest]) (*connect.Response[NotificationChannel], error)
	ListNotificationChannels(context.Context, *connect.Request[ListNotificationChannelsRequest]) (*connect.Response[ListNotificationChannelsResponse], error)
	UpdateNotificationChannel(context.Context, *connect.Request[UpdateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error)
	DeleteNotificationChannel(context.Context, *connect.Request[DeleteNotificationChannelRequest]) (*connect.Response[Empty], error)
}

// NewNotificationChannelServiceClient constructs a client for the
// blippy.notification.NotificationChannelService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationChannelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationChannelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationChannelServiceMethods := File_notification_notification_proto.Services().ByName("NotificationChannelService").Methods()
	return &notificationChannelServiceClient{
		createNotificationChannel: connect.NewClient[CreateNotificationChannelRequest, NotificationChannel](
			httpClient,
			baseURL+NotificationChannelServiceCreateNotificationChannelProcedure,
			connect.WithSchema(notificationChannelServiceMethods.ByName("CreateNotificationChannel")),
			connect.WithClientOptions(opts...),
		),
		getNotificationChannel: connect.NewClient[GetNotificationChannelRequest, NotificationChannel](
			httpClient,
			baseURL+NotificationChannelServiceGetNotificationChannelProcedure,
			connect.WithSchema(notificationChannelServiceMethods.ByName("GetNotificationChannel")),
			connect.WithClientOptions(opts...),
		),
		listNotificationChannels: connect.NewClient[ListNotificationChannelsRequest, ListNotificationChannelsResponse](
			httpClient,
			baseURL+NotificationChannelServiceListNotificationChannelsProcedure,
			connect.WithSchema(notificationChannelServiceMethods.ByName("ListNotificationChannels")),
			connect.WithClientOptions(opts...),
		),
		updateNotificationChannel: connect.NewClient[UpdateNotificationChannelRequest, NotificationChannel](
			httpClient,
			baseURL+NotificationChannelServiceUpdateNotificationChannelProcedure,
			connect.WithSchema(notificationChannelServiceMethods.ByName("UpdateNotificationChannel")),
			connect.WithClientOptions(opts...),
		),
		deleteNotificationChannel: connect.NewClient[DeleteNotificationChannelRequest, Empty](
			httpClient,
			baseURL+NotificationChannelServiceDeleteNotificationChannelProcedure,
			connect.WithSchema(notificationChannelServiceMethods.ByName("DeleteNotificationChannel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationChannelServiceClient implements NotificationChannelServiceClient.
type notificationChannelServiceClient struct {
	createNotificationChannel *connect.Client[CreateNotificationChannelRequest, NotificationChannel]
	getNotificationChannel    *connect.Client[GetNotificationChannelRequest, NotificationChannel]
	listNotificationChannels  *connect.Client[ListNotificationChannelsRequest, ListNotificationChannelsResponse]
	updateNotificationChannel *connect.Client[UpdateNotificationChannelRequest, NotificationChannel]
	deleteNotificationChannel *connect.Client[DeleteNotificationChannelRequest, Empty]
}

// CreateNotificationChannel calls
// blippy.notification.NotificationChannelService.CreateNotificationChannel.
func (c *notificationChannelServiceClient) CreateNotificationChannel(ctx context.Context, req *connect.Request[CreateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error) {
	return c.createNotificationChannel.CallUnary(ctx, req)
}

// GetNotificationChannel calls
// blippy.notification.NotificationChannelService.GetNotificationChannel.
func (c *notificationChannelServiceClient) GetNotificationChannel(ctx context.Context, req *connect.Request[GetNotificationChannelRequest]) (*connect.Response[NotificationChannel], error) {
	return c.getNotificationChannel.CallUnary(ctx, req)
}

// ListNotificationChannels calls
// blippy.notification.NotificationChannelService.ListNotificationChannels.
func (c *notificationChannelServiceClient) ListNotificationChannels(ctx context.Context, req *connect.Request[ListNotificationChannelsRequest]) (*connect.Response[ListNotificationChannelsResponse], error) {
	return c.listNotificationChannels.CallUnary(ctx, req)
}

// UpdateNotificationChannel calls
// blippy.notification.NotificationChannelService.UpdateNotificationChannel.
func (c *notificationChannelServiceClient) UpdateNotificationChannel(ctx context.Context, req *connect.Request[UpdateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error) {
	return c.updateNotificationChannel.CallUnary(ctx, req)
}

// DeleteNotificationChannel calls
// blippy.notification.NotificationChannelService.DeleteNotificationChannel.
func (c *notificationChannelServiceClient) DeleteNotificationChannel(ctx context.Context, req *connect.Request[DeleteNotificationChannelRequest]) (*connect.Response[Empty], error) {
	return c.deleteNotificationChannel.CallUnary(ctx, req)
}

// NotificationChannelServiceHandler is an implementation of the
// blippy.notification.NotificationChannelService service.
type NotificationChannelServiceHandler interface {
	CreateNotificationChannel(context.Context, *connect.Request[CreateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error)
	GetNotificationChannel(context.Context, *connect.Request[GetNotificationChannelRequest]) (*connect.Response[NotificationChannel], error)
	ListNotificationChannels(context.Context, *connect.Request[ListNotificationChannelsRequest]) (*connect.Response[ListNotificationChannelsResponse], error)
	UpdateNotificationChannel(context.Context, *connect.Request[UpdateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error)
	DeleteNotificationChannel(context.Context, *connect.Request[DeleteNotificationChannelRequest]) (*connect.Response[Empty], error)
}

// NewNotificationChannelServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationChannelServiceHandler(svc NotificationChannelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationChannelServiceMethods := File_notification_notification_proto.Services().ByName("NotificationChannelService").Methods()
	notificationChannelServiceCreateNotificationChannelHandler := connect.NewUnaryHandler(
		NotificationChannelServiceCreateNotificationChannelProcedure,
		svc.CreateNotificationChannel,
		connect.WithSchema(notificationChannelServiceMethods.ByName("CreateNotificationChannel")),
		connect.WithHandlerOptions(opts...),
	)
	notificationChannelServiceGetNotificationChannelHandler := connect.NewUnaryHandler(
		NotificationChannelServiceGetNotificationChannelProcedure,
		svc.GetNotificationChannel,
		connect.WithSchema(notificationChannelServiceMethods.ByName("GetNotificationChannel")),
		connect.WithHandlerOptions(opts...),
	)
	notificationChannelServiceListNotificationChannelsHandler := connect.NewUnaryHandler(
		NotificationChannelServiceListNotificationChannelsProcedure,
		svc.ListNotificationChannels,
		connect.WithSchema(notificationChannelServiceMethods.ByName("ListNotificationChannels")),
		connect.WithHandlerOptions(opts...),
	)
	notificationChannelServiceUpdateNotificationChannelHandler := connect.NewUnaryHandler(
		NotificationChannelServiceUpdateNotificationChannelProcedure,
		svc.UpdateNotificationChannel,
		connect.WithSchema(notificationChannelServiceMethods.ByName("UpdateNotificationChannel")),
		connect.WithHandlerOptions(opts...),
	)
	notificationChannelServiceDeleteNotificationChannelHandler := connect.NewUnaryHandler(
		NotificationChannelServiceDeleteNotificationChannelProcedure,
		svc.DeleteNotificationChannel,
		connect.WithSchema(notificationChannelServiceMethods.ByName("DeleteNotificationChannel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blippy.notification.NotificationChannelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationChannelServiceCreateNotificationChannelProcedure:
			notificationChannelServiceCreateNotificationChannelHandler.ServeHTTP(w, r)
		case NotificationChannelServiceGetNotificationChannelProcedure:
			notificationChannelServiceGetNotificationChannelHandler.ServeHTTP(w, r)
		case NotificationChannelServiceListNotificationChannelsProcedure:
			notificationChannelServiceListNotificationChannelsHandler.ServeHTTP(w, r)
		case NotificationChannelServiceUpdateNotificationChannelProcedure:
			notificationChannelServiceUpdateNotificationChannelHandler.ServeHTTP(w, r)
		case NotificationChannelServiceDeleteNotificationChannelProcedure:
			notificationChannelServiceDeleteNotificationChannelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationChannelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationChannelServiceHandler struct{}

func (UnimplementedNotificationChannelServiceHandler) CreateNotificationChannel(context.Context, *connect.Request[CreateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.notification.NotificationChannelService.CreateNotificationChannel is not implemented"))
}

func (UnimplementedNotificationChannelServiceHandler) GetNotificationChannel(context.Context, *connect.Request[GetNotificationChannelRequest]) (*connect.Response[NotificationChannel], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.notification.NotificationChannelService.GetNotificationChannel is not implemented"))
}

func (UnimplementedNotificationChannelServiceHandler) ListNotificationChannels(context.Context, *connect.Request[ListNotificationChannelsRequest]) (*connect.Response[ListNotificationChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.notification.NotificationChannelService.ListNotificationChannels is not implemented"))
}

func (UnimplementedNotificationChannelServiceHandler) UpdateNotificationChannel(context.Context, *connect.Request[UpdateNotificationChannelRequest]) (*connect.Response[NotificationChannel], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.notification.NotificationChannelService.UpdateNotificationChannel is not implemented"))
}

func (UnimplementedNotificationChannelServiceHandler) DeleteNotificationChannel(context.Context, *connect.Request[DeleteNotificationChannelRequest]) (*connect.Response[Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.notification.NotificationChannelService.DeleteNotificationChannel is not implemented"))
}
