// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Agent struct {
	ID                          string
	Name                        string
	Description                 string
	SystemPrompt                string
	EnabledTools                string
	CreatedAt                   string
	UpdatedAt                   string
	EnabledNotificationChannels string
	Model                       string
}

type Conversation struct {
	ID                 string
	AgentID            string
	Title              string
	PreviousResponseID string
	CreatedAt          string
	UpdatedAt          string
}

type Message struct {
	ID             string
	ConversationID string
	Role           string
	Content        string
	CreatedAt      string
	ToolExecutions string
}

type NotificationChannel struct {
	ID          string
	Name        string
	Type        string
	Config      string
	CreatedAt   string
	UpdatedAt   string
	Description string
	JsonSchema  string
}

type Trigger struct {
	ID        string
	AgentID   string
	Name      string
	Prompt    string
	CronExpr  sql.NullString
	Enabled   int64
	NextRunAt sql.NullString
	CreatedAt string
	UpdatedAt string
	Model     string
}

type TriggerRun struct {
	ID             string
	TriggerID      string
	ConversationID sql.NullString
	Status         string
	ErrorMessage   sql.NullString
	StartedAt      string
	FinishedAt     sql.NullString
}
