// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Agent struct {
	ID                          string
	Name                        string
	Description                 string
	SystemPrompt                string
	EnabledTools                string
	EnabledNotificationChannels string
	Model                       string
	CreatedAt                   string
	UpdatedAt                   string
	EnabledFilesystemRoots      string
	ForwardedHostEnvVars        string
}

type AgentFile struct {
	AgentID   string
	Path      string
	Content   string
	CreatedAt string
	UpdatedAt string
}

type Conversation struct {
	ID                 string
	AgentID            string
	Title              string
	PreviousResponseID string
	CreatedAt          string
	UpdatedAt          string
}

type FilesystemRoot struct {
	ID          string
	Name        string
	Path        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type Message struct {
	ID             string
	ConversationID string
	Role           string
	Items          string
	CreatedAt      string
}

type NotificationChannel struct {
	ID          string
	Name        string
	Type        string
	Config      string
	Description string
	JsonSchema  string
	CreatedAt   string
	UpdatedAt   string
}

type Trigger struct {
	ID                string
	AgentID           string
	Name              string
	Prompt            string
	CronExpr          sql.NullString
	Enabled           int64
	NextRunAt         sql.NullString
	Model             string
	ConversationTitle string
	CreatedAt         string
	UpdatedAt         string
}

type TriggerRun struct {
	ID             string
	TriggerID      string
	ConversationID sql.NullString
	Status         string
	ErrorMessage   sql.NullString
	StartedAt      string
	FinishedAt     sql.NullString
}
