// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, name, description, system_prompt, enabled_tools, enabled_notification_channels, enabled_filesystem_roots, model, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, system_prompt, enabled_tools, enabled_notification_channels, model, created_at, updated_at, enabled_filesystem_roots
`

type CreateAgentParams struct {
	ID                          string
	Name                        string
	Description                 string
	SystemPrompt                string
	EnabledTools                string
	EnabledNotificationChannels string
	EnabledFilesystemRoots      string
	Model                       string
	CreatedAt                   string
	UpdatedAt                   string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.EnabledTools,
		arg.EnabledNotificationChannels,
		arg.EnabledFilesystemRoots,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.EnabledTools,
		&i.EnabledNotificationChannels,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnabledFilesystemRoots,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, agent_id, title, previous_response_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, title, previous_response_id, created_at, updated_at
`

type CreateConversationParams struct {
	ID                 string
	AgentID            string
	Title              string
	PreviousResponseID string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.AgentID,
		arg.Title,
		arg.PreviousResponseID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.PreviousResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFilesystemRoot = `-- name: CreateFilesystemRoot :one

INSERT INTO filesystem_roots (id, name, path, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, path, description, created_at, updated_at
`

type CreateFilesystemRootParams struct {
	ID          string
	Name        string
	Path        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

// Filesystem Roots
func (q *Queries) CreateFilesystemRoot(ctx context.Context, arg CreateFilesystemRootParams) (FilesystemRoot, error) {
	row := q.db.QueryRowContext(ctx, createFilesystemRoot,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FilesystemRoot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, role, items, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, conversation_id, role, items, created_at
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	Role           string
	Items          string
	CreatedAt      string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Items,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Items,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one

INSERT INTO notification_channels (id, name, type, config, description, json_schema, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, config, description, json_schema, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	ID          string
	Name        string
	Type        string
	Config      string
	Description string
	JsonSchema  string
	CreatedAt   string
	UpdatedAt   string
}

// Notification Channels
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, createNotificationChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Description,
		arg.JsonSchema,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Description,
		&i.JsonSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrigger = `-- name: CreateTrigger :one

INSERT INTO triggers (id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at
`

type CreateTriggerParams struct {
	ID                string
	AgentID           string
	Name              string
	Prompt            string
	CronExpr          sql.NullString
	Enabled           int64
	NextRunAt         sql.NullString
	Model             string
	ConversationTitle string
	CreatedAt         string
	UpdatedAt         string
}

// Triggers
func (q *Queries) CreateTrigger(ctx context.Context, arg CreateTriggerParams) (Trigger, error) {
	row := q.db.QueryRowContext(ctx, createTrigger,
		arg.ID,
		arg.AgentID,
		arg.Name,
		arg.Prompt,
		arg.CronExpr,
		arg.Enabled,
		arg.NextRunAt,
		arg.Model,
		arg.ConversationTitle,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Trigger
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Prompt,
		&i.CronExpr,
		&i.Enabled,
		&i.NextRunAt,
		&i.Model,
		&i.ConversationTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTriggerRun = `-- name: CreateTriggerRun :one

INSERT INTO trigger_runs (id, trigger_id, conversation_id, status, error_message, started_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, trigger_id, conversation_id, status, error_message, started_at, finished_at
`

type CreateTriggerRunParams struct {
	ID             string
	TriggerID      string
	ConversationID sql.NullString
	Status         string
	ErrorMessage   sql.NullString
	StartedAt      string
	FinishedAt     sql.NullString
}

// Trigger Runs
func (q *Queries) CreateTriggerRun(ctx context.Context, arg CreateTriggerRunParams) (TriggerRun, error) {
	row := q.db.QueryRowContext(ctx, createTriggerRun,
		arg.ID,
		arg.TriggerID,
		arg.ConversationID,
		arg.Status,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i TriggerRun
	err := row.Scan(
		&i.ID,
		&i.TriggerID,
		&i.ConversationID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const deleteAgentFile = `-- name: DeleteAgentFile :exec
DELETE FROM agent_files WHERE agent_id = ? AND path = ?
`

type DeleteAgentFileParams struct {
	AgentID string
	Path    string
}

func (q *Queries) DeleteAgentFile(ctx context.Context, arg DeleteAgentFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentFile, arg.AgentID, arg.Path)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const deleteFilesystemRoot = `-- name: DeleteFilesystemRoot :exec
DELETE FROM filesystem_roots WHERE id = ?
`

func (q *Queries) DeleteFilesystemRoot(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFilesystemRoot, id)
	return err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationChannel, id)
	return err
}

const deleteTrigger = `-- name: DeleteTrigger :exec
DELETE FROM triggers WHERE id = ?
`

func (q *Queries) DeleteTrigger(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTrigger, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, description, system_prompt, enabled_tools, enabled_notification_channels, model, created_at, updated_at, enabled_filesystem_roots FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.EnabledTools,
		&i.EnabledNotificationChannels,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnabledFilesystemRoots,
	)
	return i, err
}

const getAgentFile = `-- name: GetAgentFile :one
SELECT agent_id, path, content, created_at, updated_at FROM agent_files WHERE agent_id = ? AND path = ?
`

type GetAgentFileParams struct {
	AgentID string
	Path    string
}

func (q *Queries) GetAgentFile(ctx context.Context, arg GetAgentFileParams) (AgentFile, error) {
	row := q.db.QueryRowContext(ctx, getAgentFile, arg.AgentID, arg.Path)
	var i AgentFile
	err := row.Scan(
		&i.AgentID,
		&i.Path,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, agent_id, title, previous_response_id, created_at, updated_at FROM conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.PreviousResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDueTriggers = `-- name: GetDueTriggers :many
SELECT id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at FROM triggers WHERE enabled = 1 AND next_run_at <= ? ORDER BY next_run_at ASC
`

func (q *Queries) GetDueTriggers(ctx context.Context, nextRunAt sql.NullString) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, getDueTriggers, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trigger
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Prompt,
			&i.CronExpr,
			&i.Enabled,
			&i.NextRunAt,
			&i.Model,
			&i.ConversationTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesystemRoot = `-- name: GetFilesystemRoot :one
SELECT id, name, path, description, created_at, updated_at FROM filesystem_roots WHERE id = ?
`

func (q *Queries) GetFilesystemRoot(ctx context.Context, id string) (FilesystemRoot, error) {
	row := q.db.QueryRowContext(ctx, getFilesystemRoot, id)
	var i FilesystemRoot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFilesystemRootByName = `-- name: GetFilesystemRootByName :one
SELECT id, name, path, description, created_at, updated_at FROM filesystem_roots WHERE name = ?
`

func (q *Queries) GetFilesystemRootByName(ctx context.Context, name string) (FilesystemRoot, error) {
	row := q.db.QueryRowContext(ctx, getFilesystemRootByName, name)
	var i FilesystemRoot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, role, items, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Items,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, name, type, config, description, json_schema, created_at, updated_at FROM notification_channels WHERE id = ?
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Description,
		&i.JsonSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationChannelByName = `-- name: GetNotificationChannelByName :one
SELECT id, name, type, config, description, json_schema, created_at, updated_at FROM notification_channels WHERE name = ?
`

func (q *Queries) GetNotificationChannelByName(ctx context.Context, name string) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannelByName, name)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Description,
		&i.JsonSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrigger = `-- name: GetTrigger :one
SELECT id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at FROM triggers WHERE id = ?
`

func (q *Queries) GetTrigger(ctx context.Context, id string) (Trigger, error) {
	row := q.db.QueryRowContext(ctx, getTrigger, id)
	var i Trigger
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Prompt,
		&i.CronExpr,
		&i.Enabled,
		&i.NextRunAt,
		&i.Model,
		&i.ConversationTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentFiles = `-- name: ListAgentFiles :many
SELECT agent_id, path, created_at, updated_at
FROM agent_files WHERE agent_id = ? AND path LIKE ?
ORDER BY path ASC
`

type ListAgentFilesParams struct {
	AgentID string
	Path    string
}

type ListAgentFilesRow struct {
	AgentID   string
	Path      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListAgentFiles(ctx context.Context, arg ListAgentFilesParams) ([]ListAgentFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentFiles, arg.AgentID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentFilesRow
	for rows.Next() {
		var i ListAgentFilesRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, description, system_prompt, enabled_tools, enabled_notification_channels, model, created_at, updated_at, enabled_filesystem_roots FROM agents ORDER BY created_at DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.EnabledTools,
			&i.EnabledNotificationChannels,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnabledFilesystemRoots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllConversations = `-- name: ListAllConversations :many
SELECT id, agent_id, title, previous_response_id, created_at, updated_at FROM conversations ORDER BY updated_at DESC
`

func (q *Queries) ListAllConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listAllConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.PreviousResponseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTriggers = `-- name: ListAllTriggers :many
SELECT id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at FROM triggers ORDER BY created_at DESC
`

func (q *Queries) ListAllTriggers(ctx context.Context) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listAllTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trigger
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Prompt,
			&i.CronExpr,
			&i.Enabled,
			&i.NextRunAt,
			&i.Model,
			&i.ConversationTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, agent_id, title, previous_response_id, created_at, updated_at FROM conversations WHERE agent_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, agentID string) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.PreviousResponseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesystemRoots = `-- name: ListFilesystemRoots :many
SELECT id, name, path, description, created_at, updated_at FROM filesystem_roots ORDER BY created_at DESC
`

func (q *Queries) ListFilesystemRoots(ctx context.Context) ([]FilesystemRoot, error) {
	rows, err := q.db.QueryContext(ctx, listFilesystemRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilesystemRoot
	for rows.Next() {
		var i FilesystemRoot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, name, type, config, description, json_schema, created_at, updated_at FROM notification_channels ORDER BY created_at DESC
`

func (q *Queries) ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Description,
			&i.JsonSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggerRuns = `-- name: ListTriggerRuns :many
SELECT id, trigger_id, conversation_id, status, error_message, started_at, finished_at FROM trigger_runs WHERE trigger_id = ? ORDER BY started_at DESC LIMIT ?
`

type ListTriggerRunsParams struct {
	TriggerID string
	Limit     int64
}

func (q *Queries) ListTriggerRuns(ctx context.Context, arg ListTriggerRunsParams) ([]TriggerRun, error) {
	rows, err := q.db.QueryContext(ctx, listTriggerRuns, arg.TriggerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TriggerRun
	for rows.Next() {
		var i TriggerRun
		if err := rows.Scan(
			&i.ID,
			&i.TriggerID,
			&i.ConversationID,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggersByAgent = `-- name: ListTriggersByAgent :many
SELECT id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at FROM triggers WHERE agent_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTriggersByAgent(ctx context.Context, agentID string) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listTriggersByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trigger
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Prompt,
			&i.CronExpr,
			&i.Enabled,
			&i.NextRunAt,
			&i.Model,
			&i.ConversationTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = ?, description = ?, system_prompt = ?, enabled_tools = ?, enabled_notification_channels = ?, enabled_filesystem_roots = ?, model = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, description, system_prompt, enabled_tools, enabled_notification_channels, model, created_at, updated_at, enabled_filesystem_roots
`

type UpdateAgentParams struct {
	Name                        string
	Description                 string
	SystemPrompt                string
	EnabledTools                string
	EnabledNotificationChannels string
	EnabledFilesystemRoots      string
	Model                       string
	UpdatedAt                   string
	ID                          string
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.EnabledTools,
		arg.EnabledNotificationChannels,
		arg.EnabledFilesystemRoots,
		arg.Model,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.EnabledTools,
		&i.EnabledNotificationChannels,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnabledFilesystemRoots,
	)
	return i, err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET title = ?, previous_response_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, agent_id, title, previous_response_id, created_at, updated_at
`

type UpdateConversationParams struct {
	Title              string
	PreviousResponseID string
	UpdatedAt          string
	ID                 string
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversation,
		arg.Title,
		arg.PreviousResponseID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.PreviousResponseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFilesystemRoot = `-- name: UpdateFilesystemRoot :one
UPDATE filesystem_roots SET name = ?, path = ?, description = ?, updated_at = ?
WHERE id = ? RETURNING id, name, path, description, created_at, updated_at
`

type UpdateFilesystemRootParams struct {
	Name        string
	Path        string
	Description string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateFilesystemRoot(ctx context.Context, arg UpdateFilesystemRootParams) (FilesystemRoot, error) {
	row := q.db.QueryRowContext(ctx, updateFilesystemRoot,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i FilesystemRoot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels SET name = ?, type = ?, config = ?, description = ?, json_schema = ?, updated_at = ?
WHERE id = ? RETURNING id, name, type, config, description, json_schema, created_at, updated_at
`

type UpdateNotificationChannelParams struct {
	Name        string
	Type        string
	Config      string
	Description string
	JsonSchema  string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Description,
		arg.JsonSchema,
		arg.UpdatedAt,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Description,
		&i.JsonSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrigger = `-- name: UpdateTrigger :one
UPDATE triggers SET name = ?, prompt = ?, cron_expr = ?, enabled = ?, next_run_at = ?, updated_at = ?
WHERE id = ? RETURNING id, agent_id, name, prompt, cron_expr, enabled, next_run_at, model, conversation_title, created_at, updated_at
`

type UpdateTriggerParams struct {
	Name      string
	Prompt    string
	CronExpr  sql.NullString
	Enabled   int64
	NextRunAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateTrigger(ctx context.Context, arg UpdateTriggerParams) (Trigger, error) {
	row := q.db.QueryRowContext(ctx, updateTrigger,
		arg.Name,
		arg.Prompt,
		arg.CronExpr,
		arg.Enabled,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Trigger
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Prompt,
		&i.CronExpr,
		&i.Enabled,
		&i.NextRunAt,
		&i.Model,
		&i.ConversationTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTriggerNextRun = `-- name: UpdateTriggerNextRun :exec
UPDATE triggers SET next_run_at = ?, updated_at = ? WHERE id = ?
`

type UpdateTriggerNextRunParams struct {
	NextRunAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateTriggerNextRun(ctx context.Context, arg UpdateTriggerNextRunParams) error {
	_, err := q.db.ExecContext(ctx, updateTriggerNextRun, arg.NextRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateTriggerRun = `-- name: UpdateTriggerRun :exec
UPDATE trigger_runs SET status = ?, error_message = ?, conversation_id = ?, finished_at = ?
WHERE id = ?
`

type UpdateTriggerRunParams struct {
	Status         string
	ErrorMessage   sql.NullString
	ConversationID sql.NullString
	FinishedAt     sql.NullString
	ID             string
}

func (q *Queries) UpdateTriggerRun(ctx context.Context, arg UpdateTriggerRunParams) error {
	_, err := q.db.ExecContext(ctx, updateTriggerRun,
		arg.Status,
		arg.ErrorMessage,
		arg.ConversationID,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const upsertAgentFile = `-- name: UpsertAgentFile :one

INSERT INTO agent_files (agent_id, path, content, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (agent_id, path) DO UPDATE SET content = excluded.content, updated_at = excluded.updated_at
RETURNING agent_id, path, content, created_at, updated_at
`

type UpsertAgentFileParams struct {
	AgentID   string
	Path      string
	Content   string
	CreatedAt string
	UpdatedAt string
}

// Agent Files
func (q *Queries) UpsertAgentFile(ctx context.Context, arg UpsertAgentFileParams) (AgentFile, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentFile,
		arg.AgentID,
		arg.Path,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentFile
	err := row.Scan(
		&i.AgentID,
		&i.Path,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
