// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conversation/conversation.proto

package conversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PreviousResponseId string                 `protobuf:"bytes,4,opt,name=previous_response_id,json=previousResponseId,proto3" json:"previous_response_id,omitempty"` // OpenResponses chaining
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_conversation_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetPreviousResponseId() string {
	if x != nil {
		return x.PreviousResponseId
	}
	return ""
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "user", "assistant", "system"
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ToolExecutions []*StoredToolExecution `protobuf:"bytes,6,rep,name=tool_executions,json=toolExecutions,proto3" json:"tool_executions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_conversation_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetToolExecutions() []*StoredToolExecution {
	if x != nil {
		return x.ToolExecutions
	}
	return nil
}

type StoredToolExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // tool name (e.g., "bash")
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`   // tool input/arguments as JSON
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // tool output
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredToolExecution) Reset() {
	*x = StoredToolExecution{}
	mi := &file_conversation_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredToolExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredToolExecution) ProtoMessage() {}

func (x *StoredToolExecution) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredToolExecution.ProtoReflect.Descriptor instead.
func (*StoredToolExecution) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *StoredToolExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoredToolExecution) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *StoredToolExecution) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConversationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversationsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type DeleteConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Streaming response events
type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatEvent_Delta
	//	*ChatEvent_Done
	//	*ChatEvent_Error
	//	*ChatEvent_ToolExecution
	Event         isChatEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_conversation_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *ChatEvent) GetEvent() isChatEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatEvent) GetDelta() *ChatDelta {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *ChatEvent) GetDone() *ChatDone {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ChatEvent) GetError() *ChatError {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ChatEvent) GetToolExecution() *ToolExecution {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolExecution); ok {
			return x.ToolExecution
		}
	}
	return nil
}

type isChatEvent_Event interface {
	isChatEvent_Event()
}

type ChatEvent_Delta struct {
	Delta *ChatDelta `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type ChatEvent_Done struct {
	Done *ChatDone `protobuf:"bytes,2,opt,name=done,proto3,oneof"`
}

type ChatEvent_Error struct {
	Error *ChatError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ChatEvent_ToolExecution struct {
	ToolExecution *ToolExecution `protobuf:"bytes,4,opt,name=tool_execution,json=toolExecution,proto3,oneof"`
}

func (*ChatEvent_Delta) isChatEvent_Event() {}

func (*ChatEvent_Done) isChatEvent_Event() {}

func (*ChatEvent_Error) isChatEvent_Event() {}

func (*ChatEvent_ToolExecution) isChatEvent_Event() {}

type ChatDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // partial token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatDelta) Reset() {
	*x = ChatDelta{}
	mi := &file_conversation_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDelta) ProtoMessage() {}

func (x *ChatDelta) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDelta.ProtoReflect.Descriptor instead.
func (*ChatDelta) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *ChatDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatDone struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserMessageId      string                 `protobuf:"bytes,1,opt,name=user_message_id,json=userMessageId,proto3" json:"user_message_id,omitempty"`
	AssistantMessageId string                 `protobuf:"bytes,2,opt,name=assistant_message_id,json=assistantMessageId,proto3" json:"assistant_message_id,omitempty"`
	ResponseId         string                 `protobuf:"bytes,3,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"` // OpenResponses response_id for chaining
	Title              string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                             // Set when title was generated (first turn only)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChatDone) Reset() {
	*x = ChatDone{}
	mi := &file_conversation_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDone) ProtoMessage() {}

func (x *ChatDone) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDone.ProtoReflect.Descriptor instead.
func (*ChatDone) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *ChatDone) GetUserMessageId() string {
	if x != nil {
		return x.UserMessageId
	}
	return ""
}

func (x *ChatDone) GetAssistantMessageId() string {
	if x != nil {
		return x.AssistantMessageId
	}
	return ""
}

func (x *ChatDone) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ChatDone) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ChatError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatError) Reset() {
	*x = ChatError{}
	mi := &file_conversation_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatError) ProtoMessage() {}

func (x *ChatError) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatError.ProtoReflect.Descriptor instead.
func (*ChatError) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *ChatError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ToolExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // tool name (e.g., "bash", "fetch_url")
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "executing", "completed", "error"
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // tool output (when completed)
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`   // tool input/arguments as JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecution) Reset() {
	*x = ToolExecution{}
	mi := &file_conversation_conversation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecution) ProtoMessage() {}

func (x *ToolExecution) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecution.ProtoReflect.Descriptor instead.
func (*ToolExecution) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{15}
}

func (x *ToolExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolExecution) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolExecution) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_conversation_conversation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{16}
}

var File_conversation_conversation_proto protoreflect.FileDescriptor

const file_conversation_conversation_proto_rawDesc = "" +
	"\n" +
	"\x1fconversation/conversation.proto\x12\x13blippy.conversation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x120\n" +
	"\x14previous_response_id\x18\x04 \x01(\tR\x12previousResponseId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfe\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12Q\n" +
	"\x0ftool_executions\x18\x06 \x03(\v2(.blippy.conversation.StoredToolExecutionR\x0etoolExecutions\"W\n" +
	"\x13StoredToolExecution\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"6\n" +
	"\x19CreateConversationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"(\n" +
	"\x16GetConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x18ListConversationsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"d\n" +
	"\x19ListConversationsResponse\x12G\n" +
	"\rconversations\x18\x01 \x03(\v2!.blippy.conversation.ConversationR\rconversations\"+\n" +
	"\x19DeleteConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12GetMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"O\n" +
	"\x13GetMessagesResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.blippy.conversation.MessageR\bmessages\"P\n" +
	"\vChatRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x86\x02\n" +
	"\tChatEvent\x126\n" +
	"\x05delta\x18\x01 \x01(\v2\x1e.blippy.conversation.ChatDeltaH\x00R\x05delta\x123\n" +
	"\x04done\x18\x02 \x01(\v2\x1d.blippy.conversation.ChatDoneH\x00R\x04done\x126\n" +
	"\x05error\x18\x03 \x01(\v2\x1e.blippy.conversation.ChatErrorH\x00R\x05error\x12K\n" +
	"\x0etool_execution\x18\x04 \x01(\v2\".blippy.conversation.ToolExecutionH\x00R\rtoolExecutionB\a\n" +
	"\x05event\"%\n" +
	"\tChatDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x9b\x01\n" +
	"\bChatDone\x12&\n" +
	"\x0fuser_message_id\x18\x01 \x01(\tR\ruserMessageId\x120\n" +
	"\x14assistant_message_id\x18\x02 \x01(\tR\x12assistantMessageId\x12\x1f\n" +
	"\vresponse_id\x18\x03 \x01(\tR\n" +
	"responseId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"%\n" +
	"\tChatError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"i\n" +
	"\rToolExecution\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\"\a\n" +
	"\x05Empty2\xe5\x04\n" +
	"\x13ConversationService\x12g\n" +
	"\x12CreateConversation\x12..blippy.conversation.CreateConversationRequest\x1a!.blippy.conversation.Conversation\x12a\n" +
	"\x0fGetConversation\x12+.blippy.conversation.GetConversationRequest\x1a!.blippy.conversation.Conversation\x12r\n" +
	"\x11ListConversations\x12-.blippy.conversation.ListConversationsRequest\x1a..blippy.conversation.ListConversationsResponse\x12`\n" +
	"\x12DeleteConversation\x12..blippy.conversation.DeleteConversationRequest\x1a\x1a.blippy.conversation.Empty\x12`\n" +
	"\vGetMessages\x12'.blippy.conversation.GetMessagesRequest\x1a(.blippy.conversation.GetMessagesResponse\x12J\n" +
	"\x04Chat\x12 .blippy.conversation.ChatRequest\x1a\x1e.blippy.conversation.ChatEvent0\x01B2Z0github.com/dstotijn/blippy/internal/conversationb\x06proto3"

var (
	file_conversation_conversation_proto_rawDescOnce sync.Once
	file_conversation_conversation_proto_rawDescData []byte
)

func file_conversation_conversation_proto_rawDescGZIP() []byte {
	file_conversation_conversation_proto_rawDescOnce.Do(func() {
		file_conversation_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_conversation_proto_rawDesc), len(file_conversation_conversation_proto_rawDesc)))
	})
	return file_conversation_conversation_proto_rawDescData
}

var file_conversation_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_conversation_conversation_proto_goTypes = []any{
	(*Conversation)(nil),              // 0: blippy.conversation.Conversation
	(*Message)(nil),                   // 1: blippy.conversation.Message
	(*StoredToolExecution)(nil),       // 2: blippy.conversation.StoredToolExecution
	(*CreateConversationRequest)(nil), // 3: blippy.conversation.CreateConversationRequest
	(*GetConversationRequest)(nil),    // 4: blippy.conversation.GetConversationRequest
	(*ListConversationsRequest)(nil),  // 5: blippy.conversation.ListConversationsRequest
	(*ListConversationsResponse)(nil), // 6: blippy.conversation.ListConversationsResponse
	(*DeleteConversationRequest)(nil), // 7: blippy.conversation.DeleteConversationRequest
	(*GetMessagesRequest)(nil),        // 8: blippy.conversation.GetMessagesRequest
	(*GetMessagesResponse)(nil),       // 9: blippy.conversation.GetMessagesResponse
	(*ChatRequest)(nil),               // 10: blippy.conversation.ChatRequest
	(*ChatEvent)(nil),                 // 11: blippy.conversation.ChatEvent
	(*ChatDelta)(nil),                 // 12: blippy.conversation.ChatDelta
	(*ChatDone)(nil),                  // 13: blippy.conversation.ChatDone
	(*ChatError)(nil),                 // 14: blippy.conversation.ChatError
	(*ToolExecution)(nil),             // 15: blippy.conversation.ToolExecution
	(*Empty)(nil),                     // 16: blippy.conversation.Empty
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_conversation_conversation_proto_depIdxs = []int32{
	17, // 0: blippy.conversation.Conversation.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: blippy.conversation.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	17, // 2: blippy.conversation.Message.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: blippy.conversation.Message.tool_executions:type_name -> blippy.conversation.StoredToolExecution
	0,  // 4: blippy.conversation.ListConversationsResponse.conversations:type_name -> blippy.conversation.Conversation
	1,  // 5: blippy.conversation.GetMessagesResponse.messages:type_name -> blippy.conversation.Message
	12, // 6: blippy.conversation.ChatEvent.delta:type_name -> blippy.conversation.ChatDelta
	13, // 7: blippy.conversation.ChatEvent.done:type_name -> blippy.conversation.ChatDone
	14, // 8: blippy.conversation.ChatEvent.error:type_name -> blippy.conversation.ChatError
	15, // 9: blippy.conversation.ChatEvent.tool_execution:type_name -> blippy.conversation.ToolExecution
	3,  // 10: blippy.conversation.ConversationService.CreateConversation:input_type -> blippy.conversation.CreateConversationRequest
	4,  // 11: blippy.conversation.ConversationService.GetConversation:input_type -> blippy.conversation.GetConversationRequest
	5,  // 12: blippy.conversation.ConversationService.ListConversations:input_type -> blippy.conversation.ListConversationsRequest
	7,  // 13: blippy.conversation.ConversationService.DeleteConversation:input_type -> blippy.conversation.DeleteConversationRequest
	8,  // 14: blippy.conversation.ConversationService.GetMessages:input_type -> blippy.conversation.GetMessagesRequest
	10, // 15: blippy.conversation.ConversationService.Chat:input_type -> blippy.conversation.ChatRequest
	0,  // 16: blippy.conversation.ConversationService.CreateConversation:output_type -> blippy.conversation.Conversation
	0,  // 17: blippy.conversation.ConversationService.GetConversation:output_type -> blippy.conversation.Conversation
	6,  // 18: blippy.conversation.ConversationService.ListConversations:output_type -> blippy.conversation.ListConversationsResponse
	16, // 19: blippy.conversation.ConversationService.DeleteConversation:output_type -> blippy.conversation.Empty
	9,  // 20: blippy.conversation.ConversationService.GetMessages:output_type -> blippy.conversation.GetMessagesResponse
	11, // 21: blippy.conversation.ConversationService.Chat:output_type -> blippy.conversation.ChatEvent
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_conversation_conversation_proto_init() }
func file_conversation_conversation_proto_init() {
	if File_conversation_conversation_proto != nil {
		return
	}
	file_conversation_conversation_proto_msgTypes[11].OneofWrappers = []any{
		(*ChatEvent_Delta)(nil),
		(*ChatEvent_Done)(nil),
		(*ChatEvent_Error)(nil),
		(*ChatEvent_ToolExecution)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_conversation_proto_rawDesc), len(file_conversation_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_conversation_proto_depIdxs,
		MessageInfos:      file_conversation_conversation_proto_msgTypes,
	}.Build()
	File_conversation_conversation_proto = out.File
	file_conversation_conversation_proto_goTypes = nil
	file_conversation_conversation_proto_depIdxs = nil
}
