// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conversation/conversation.proto

package conversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PreviousResponseId string                 `protobuf:"bytes,4,opt,name=previous_response_id,json=previousResponseId,proto3" json:"previous_response_id,omitempty"` // OpenResponses chaining
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_conversation_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetPreviousResponseId() string {
	if x != nil {
		return x.PreviousResponseId
	}
	return ""
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "user", "assistant", "system"
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Items          []*MessageItem         `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_conversation_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetItems() []*MessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MessageItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*MessageItem_Text
	//	*MessageItem_ToolExecution
	Item          isMessageItem_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_conversation_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *MessageItem) GetItem() isMessageItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *MessageItem) GetText() *TextItem {
	if x != nil {
		if x, ok := x.Item.(*MessageItem_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *MessageItem) GetToolExecution() *ToolExecutionItem {
	if x != nil {
		if x, ok := x.Item.(*MessageItem_ToolExecution); ok {
			return x.ToolExecution
		}
	}
	return nil
}

type isMessageItem_Item interface {
	isMessageItem_Item()
}

type MessageItem_Text struct {
	Text *TextItem `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageItem_ToolExecution struct {
	ToolExecution *ToolExecutionItem `protobuf:"bytes,2,opt,name=tool_execution,json=toolExecution,proto3,oneof"`
}

func (*MessageItem_Text) isMessageItem_Item() {}

func (*MessageItem_ToolExecution) isMessageItem_Item() {}

type TextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	mi := &file_conversation_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *TextItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToolExecutionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionItem) Reset() {
	*x = ToolExecutionItem{}
	mi := &file_conversation_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionItem) ProtoMessage() {}

func (x *ToolExecutionItem) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionItem.ProtoReflect.Descriptor instead.
func (*ToolExecutionItem) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *ToolExecutionItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolExecutionItem) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolExecutionItem) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateConversationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *ListConversationsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type DeleteConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMessageId string                 `protobuf:"bytes,1,opt,name=user_message_id,json=userMessageId,proto3" json:"user_message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_conversation_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *ChatResponse) GetUserMessageId() string {
	if x != nil {
		return x.UserMessageId
	}
	return ""
}

// WatchEvents streaming events
type WatchEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_conversation_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *WatchEventsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type WatchEventsEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchEventsEvent_TextDelta
	//	*WatchEventsEvent_ToolResult
	//	*WatchEventsEvent_MessageCreated
	//	*WatchEventsEvent_Error
	//	*WatchEventsEvent_Done
	//	*WatchEventsEvent_TurnStarted
	Event         isWatchEventsEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsEvent) Reset() {
	*x = WatchEventsEvent{}
	mi := &file_conversation_conversation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsEvent) ProtoMessage() {}

func (x *WatchEventsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsEvent.ProtoReflect.Descriptor instead.
func (*WatchEventsEvent) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{15}
}

func (x *WatchEventsEvent) GetEvent() isWatchEventsEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchEventsEvent) GetTextDelta() *TextDelta {
	if x != nil {
		if x, ok := x.Event.(*WatchEventsEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return nil
}

func (x *WatchEventsEvent) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*WatchEventsEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *WatchEventsEvent) GetMessageCreated() *MessageCreated {
	if x != nil {
		if x, ok := x.Event.(*WatchEventsEvent_MessageCreated); ok {
			return x.MessageCreated
		}
	}
	return nil
}

func (x *WatchEventsEvent) GetError() *WatchError {
	if x != nil {
		if x, ok := x.Event.(*WatchEventsEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WatchEventsEvent) GetDone() *TurnDone {
	if x != nil {
		if x, ok := x.Event.(*WatchEventsEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *WatchEventsEvent) GetTurnStarted() *TurnStarted {
	if x != nil {
		if x, ok := x.Event.(*WatchEventsEvent_TurnStarted); ok {
			return x.TurnStarted
		}
	}
	return nil
}

type isWatchEventsEvent_Event interface {
	isWatchEventsEvent_Event()
}

type WatchEventsEvent_TextDelta struct {
	TextDelta *TextDelta `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type WatchEventsEvent_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,2,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type WatchEventsEvent_MessageCreated struct {
	MessageCreated *MessageCreated `protobuf:"bytes,3,opt,name=message_created,json=messageCreated,proto3,oneof"`
}

type WatchEventsEvent_Error struct {
	Error *WatchError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type WatchEventsEvent_Done struct {
	Done *TurnDone `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

type WatchEventsEvent_TurnStarted struct {
	TurnStarted *TurnStarted `protobuf:"bytes,6,opt,name=turn_started,json=turnStarted,proto3,oneof"`
}

func (*WatchEventsEvent_TextDelta) isWatchEventsEvent_Event() {}

func (*WatchEventsEvent_ToolResult) isWatchEventsEvent_Event() {}

func (*WatchEventsEvent_MessageCreated) isWatchEventsEvent_Event() {}

func (*WatchEventsEvent_Error) isWatchEventsEvent_Event() {}

func (*WatchEventsEvent_Done) isWatchEventsEvent_Event() {}

func (*WatchEventsEvent_TurnStarted) isWatchEventsEvent_Event() {}

type TextDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDelta) Reset() {
	*x = TextDelta{}
	mi := &file_conversation_conversation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDelta) ProtoMessage() {}

func (x *TextDelta) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDelta.ProtoReflect.Descriptor instead.
func (*TextDelta) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{16}
}

func (x *TextDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_conversation_conversation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{17}
}

func (x *ToolResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolResult) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type MessageCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCreated) Reset() {
	*x = MessageCreated{}
	mi := &file_conversation_conversation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreated) ProtoMessage() {}

func (x *MessageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreated.ProtoReflect.Descriptor instead.
func (*MessageCreated) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{18}
}

func (x *MessageCreated) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type WatchError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchError) Reset() {
	*x = WatchError{}
	mi := &file_conversation_conversation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchError) ProtoMessage() {}

func (x *WatchError) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchError.ProtoReflect.Descriptor instead.
func (*WatchError) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{19}
}

func (x *WatchError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TurnDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnDone) Reset() {
	*x = TurnDone{}
	mi := &file_conversation_conversation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnDone) ProtoMessage() {}

func (x *TurnDone) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnDone.ProtoReflect.Descriptor instead.
func (*TurnDone) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{20}
}

func (x *TurnDone) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type TurnStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnStarted) Reset() {
	*x = TurnStarted{}
	mi := &file_conversation_conversation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnStarted) ProtoMessage() {}

func (x *TurnStarted) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnStarted.ProtoReflect.Descriptor instead.
func (*TurnStarted) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{21}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_conversation_conversation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_conversation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_conversation_conversation_proto_rawDescGZIP(), []int{22}
}

var File_conversation_conversation_proto protoreflect.FileDescriptor

const file_conversation_conversation_proto_rawDesc = "" +
	"\n" +
	"\x1fconversation/conversation.proto\x12\x13blippy.conversation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x120\n" +
	"\x14previous_response_id\x18\x04 \x01(\tR\x12previousResponseId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc9\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\x05items\x18\a \x03(\v2 .blippy.conversation.MessageItemR\x05items\"\x9b\x01\n" +
	"\vMessageItem\x123\n" +
	"\x04text\x18\x01 \x01(\v2\x1d.blippy.conversation.TextItemH\x00R\x04text\x12O\n" +
	"\x0etool_execution\x18\x02 \x01(\v2&.blippy.conversation.ToolExecutionItemH\x00R\rtoolExecutionB\x06\n" +
	"\x04item\"$\n" +
	"\bTextItem\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"U\n" +
	"\x11ToolExecutionItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"6\n" +
	"\x19CreateConversationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"(\n" +
	"\x16GetConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x18ListConversationsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"d\n" +
	"\x19ListConversationsResponse\x12G\n" +
	"\rconversations\x18\x01 \x03(\v2!.blippy.conversation.ConversationR\rconversations\"+\n" +
	"\x19DeleteConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12GetMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"O\n" +
	"\x13GetMessagesResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.blippy.conversation.MessageR\bmessages\"P\n" +
	"\vChatRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"6\n" +
	"\fChatResponse\x12&\n" +
	"\x0fuser_message_id\x18\x01 \x01(\tR\ruserMessageId\"=\n" +
	"\x12WatchEventsRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\xa5\x03\n" +
	"\x10WatchEventsEvent\x12?\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\v2\x1e.blippy.conversation.TextDeltaH\x00R\ttextDelta\x12B\n" +
	"\vtool_result\x18\x02 \x01(\v2\x1f.blippy.conversation.ToolResultH\x00R\n" +
	"toolResult\x12N\n" +
	"\x0fmessage_created\x18\x03 \x01(\v2#.blippy.conversation.MessageCreatedH\x00R\x0emessageCreated\x127\n" +
	"\x05error\x18\x04 \x01(\v2\x1f.blippy.conversation.WatchErrorH\x00R\x05error\x123\n" +
	"\x04done\x18\x05 \x01(\v2\x1d.blippy.conversation.TurnDoneH\x00R\x04done\x12E\n" +
	"\fturn_started\x18\x06 \x01(\v2 .blippy.conversation.TurnStartedH\x00R\vturnStartedB\a\n" +
	"\x05event\"%\n" +
	"\tTextDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"N\n" +
	"\n" +
	"ToolResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"H\n" +
	"\x0eMessageCreated\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.blippy.conversation.MessageR\amessage\"&\n" +
	"\n" +
	"WatchError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\" \n" +
	"\bTurnDone\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\r\n" +
	"\vTurnStarted\"\a\n" +
	"\x05Empty2\xc7\x05\n" +
	"\x13ConversationService\x12g\n" +
	"\x12CreateConversation\x12..blippy.conversation.CreateConversationRequest\x1a!.blippy.conversation.Conversation\x12a\n" +
	"\x0fGetConversation\x12+.blippy.conversation.GetConversationRequest\x1a!.blippy.conversation.Conversation\x12r\n" +
	"\x11ListConversations\x12-.blippy.conversation.ListConversationsRequest\x1a..blippy.conversation.ListConversationsResponse\x12`\n" +
	"\x12DeleteConversation\x12..blippy.conversation.DeleteConversationRequest\x1a\x1a.blippy.conversation.Empty\x12`\n" +
	"\vGetMessages\x12'.blippy.conversation.GetMessagesRequest\x1a(.blippy.conversation.GetMessagesResponse\x12K\n" +
	"\x04Chat\x12 .blippy.conversation.ChatRequest\x1a!.blippy.conversation.ChatResponse\x12_\n" +
	"\vWatchEvents\x12'.blippy.conversation.WatchEventsRequest\x1a%.blippy.conversation.WatchEventsEvent0\x01B2Z0github.com/dstotijn/blippy/internal/conversationb\x06proto3"

var (
	file_conversation_conversation_proto_rawDescOnce sync.Once
	file_conversation_conversation_proto_rawDescData []byte
)

func file_conversation_conversation_proto_rawDescGZIP() []byte {
	file_conversation_conversation_proto_rawDescOnce.Do(func() {
		file_conversation_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_conversation_proto_rawDesc), len(file_conversation_conversation_proto_rawDesc)))
	})
	return file_conversation_conversation_proto_rawDescData
}

var file_conversation_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_conversation_conversation_proto_goTypes = []any{
	(*Conversation)(nil),              // 0: blippy.conversation.Conversation
	(*Message)(nil),                   // 1: blippy.conversation.Message
	(*MessageItem)(nil),               // 2: blippy.conversation.MessageItem
	(*TextItem)(nil),                  // 3: blippy.conversation.TextItem
	(*ToolExecutionItem)(nil),         // 4: blippy.conversation.ToolExecutionItem
	(*CreateConversationRequest)(nil), // 5: blippy.conversation.CreateConversationRequest
	(*GetConversationRequest)(nil),    // 6: blippy.conversation.GetConversationRequest
	(*ListConversationsRequest)(nil),  // 7: blippy.conversation.ListConversationsRequest
	(*ListConversationsResponse)(nil), // 8: blippy.conversation.ListConversationsResponse
	(*DeleteConversationRequest)(nil), // 9: blippy.conversation.DeleteConversationRequest
	(*GetMessagesRequest)(nil),        // 10: blippy.conversation.GetMessagesRequest
	(*GetMessagesResponse)(nil),       // 11: blippy.conversation.GetMessagesResponse
	(*ChatRequest)(nil),               // 12: blippy.conversation.ChatRequest
	(*ChatResponse)(nil),              // 13: blippy.conversation.ChatResponse
	(*WatchEventsRequest)(nil),        // 14: blippy.conversation.WatchEventsRequest
	(*WatchEventsEvent)(nil),          // 15: blippy.conversation.WatchEventsEvent
	(*TextDelta)(nil),                 // 16: blippy.conversation.TextDelta
	(*ToolResult)(nil),                // 17: blippy.conversation.ToolResult
	(*MessageCreated)(nil),            // 18: blippy.conversation.MessageCreated
	(*WatchError)(nil),                // 19: blippy.conversation.WatchError
	(*TurnDone)(nil),                  // 20: blippy.conversation.TurnDone
	(*TurnStarted)(nil),               // 21: blippy.conversation.TurnStarted
	(*Empty)(nil),                     // 22: blippy.conversation.Empty
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
}
var file_conversation_conversation_proto_depIdxs = []int32{
	23, // 0: blippy.conversation.Conversation.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: blippy.conversation.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	23, // 2: blippy.conversation.Message.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: blippy.conversation.Message.items:type_name -> blippy.conversation.MessageItem
	3,  // 4: blippy.conversation.MessageItem.text:type_name -> blippy.conversation.TextItem
	4,  // 5: blippy.conversation.MessageItem.tool_execution:type_name -> blippy.conversation.ToolExecutionItem
	0,  // 6: blippy.conversation.ListConversationsResponse.conversations:type_name -> blippy.conversation.Conversation
	1,  // 7: blippy.conversation.GetMessagesResponse.messages:type_name -> blippy.conversation.Message
	16, // 8: blippy.conversation.WatchEventsEvent.text_delta:type_name -> blippy.conversation.TextDelta
	17, // 9: blippy.conversation.WatchEventsEvent.tool_result:type_name -> blippy.conversation.ToolResult
	18, // 10: blippy.conversation.WatchEventsEvent.message_created:type_name -> blippy.conversation.MessageCreated
	19, // 11: blippy.conversation.WatchEventsEvent.error:type_name -> blippy.conversation.WatchError
	20, // 12: blippy.conversation.WatchEventsEvent.done:type_name -> blippy.conversation.TurnDone
	21, // 13: blippy.conversation.WatchEventsEvent.turn_started:type_name -> blippy.conversation.TurnStarted
	1,  // 14: blippy.conversation.MessageCreated.message:type_name -> blippy.conversation.Message
	5,  // 15: blippy.conversation.ConversationService.CreateConversation:input_type -> blippy.conversation.CreateConversationRequest
	6,  // 16: blippy.conversation.ConversationService.GetConversation:input_type -> blippy.conversation.GetConversationRequest
	7,  // 17: blippy.conversation.ConversationService.ListConversations:input_type -> blippy.conversation.ListConversationsRequest
	9,  // 18: blippy.conversation.ConversationService.DeleteConversation:input_type -> blippy.conversation.DeleteConversationRequest
	10, // 19: blippy.conversation.ConversationService.GetMessages:input_type -> blippy.conversation.GetMessagesRequest
	12, // 20: blippy.conversation.ConversationService.Chat:input_type -> blippy.conversation.ChatRequest
	14, // 21: blippy.conversation.ConversationService.WatchEvents:input_type -> blippy.conversation.WatchEventsRequest
	0,  // 22: blippy.conversation.ConversationService.CreateConversation:output_type -> blippy.conversation.Conversation
	0,  // 23: blippy.conversation.ConversationService.GetConversation:output_type -> blippy.conversation.Conversation
	8,  // 24: blippy.conversation.ConversationService.ListConversations:output_type -> blippy.conversation.ListConversationsResponse
	22, // 25: blippy.conversation.ConversationService.DeleteConversation:output_type -> blippy.conversation.Empty
	11, // 26: blippy.conversation.ConversationService.GetMessages:output_type -> blippy.conversation.GetMessagesResponse
	13, // 27: blippy.conversation.ConversationService.Chat:output_type -> blippy.conversation.ChatResponse
	15, // 28: blippy.conversation.ConversationService.WatchEvents:output_type -> blippy.conversation.WatchEventsEvent
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_conversation_conversation_proto_init() }
func file_conversation_conversation_proto_init() {
	if File_conversation_conversation_proto != nil {
		return
	}
	file_conversation_conversation_proto_msgTypes[2].OneofWrappers = []any{
		(*MessageItem_Text)(nil),
		(*MessageItem_ToolExecution)(nil),
	}
	file_conversation_conversation_proto_msgTypes[15].OneofWrappers = []any{
		(*WatchEventsEvent_TextDelta)(nil),
		(*WatchEventsEvent_ToolResult)(nil),
		(*WatchEventsEvent_MessageCreated)(nil),
		(*WatchEventsEvent_Error)(nil),
		(*WatchEventsEvent_Done)(nil),
		(*WatchEventsEvent_TurnStarted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_conversation_proto_rawDesc), len(file_conversation_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_conversation_proto_depIdxs,
		MessageInfos:      file_conversation_conversation_proto_msgTypes,
	}.Build()
	File_conversation_conversation_proto = out.File
	file_conversation_conversation_proto_goTypes = nil
	file_conversation_conversation_proto_depIdxs = nil
}
