// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: conversation/conversation.proto

package conversation

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConversationServiceName is the fully-qualified name of the ConversationService service.
	ConversationServiceName = "blippy.conversation.ConversationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConversationServiceCreateConversationProcedure is the fully-qualified name of the
	// ConversationService's CreateConversation RPC.
	ConversationServiceCreateConversationProcedure = "/blippy.conversation.ConversationService/CreateConversation"
	// ConversationServiceGetConversationProcedure is the fully-qualified name of the
	// ConversationService's GetConversation RPC.
	ConversationServiceGetConversationProcedure = "/blippy.conversation.ConversationService/GetConversation"
	// ConversationServiceListConversationsProcedure is the fully-qualified name of the
	// ConversationService's ListConversations RPC.
	ConversationServiceListConversationsProcedure = "/blippy.conversation.ConversationService/ListConversations"
	// ConversationServiceDeleteConversationProcedure is the fully-qualified name of the
	// ConversationService's DeleteConversation RPC.
	ConversationServiceDeleteConversationProcedure = "/blippy.conversation.ConversationService/DeleteConversation"
	// ConversationServiceGetMessagesProcedure is the fully-qualified name of the ConversationService's
	// GetMessages RPC.
	ConversationServiceGetMessagesProcedure = "/blippy.conversation.ConversationService/GetMessages"
	// ConversationServiceChatProcedure is the fully-qualified name of the ConversationService's Chat
	// RPC.
	ConversationServiceChatProcedure = "/blippy.conversation.ConversationService/Chat"
)

// ConversationServiceClient is a client for the blippy.conversation.ConversationService service.
type ConversationServiceClient interface {
	CreateConversation(context.Context, *connect.Request[CreateConversationRequest]) (*connect.Response[Conversation], error)
	GetConversation(context.Context, *connect.Request[GetConversationRequest]) (*connect.Response[Conversation], error)
	ListConversations(context.Context, *connect.Request[ListConversationsRequest]) (*connect.Response[ListConversationsResponse], error)
	DeleteConversation(context.Context, *connect.Request[DeleteConversationRequest]) (*connect.Response[Empty], error)
	GetMessages(context.Context, *connect.Request[GetMessagesRequest]) (*connect.Response[GetMessagesResponse], error)
	Chat(context.Context, *connect.Request[ChatRequest]) (*connect.ServerStreamForClient[ChatEvent], error)
}

// NewConversationServiceClient constructs a client for the blippy.conversation.ConversationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConversationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConversationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	conversationServiceMethods := File_conversation_conversation_proto.Services().ByName("ConversationService").Methods()
	return &conversationServiceClient{
		createConversation: connect.NewClient[CreateConversationRequest, Conversation](
			httpClient,
			baseURL+ConversationServiceCreateConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("CreateConversation")),
			connect.WithClientOptions(opts...),
		),
		getConversation: connect.NewClient[GetConversationRequest, Conversation](
			httpClient,
			baseURL+ConversationServiceGetConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("GetConversation")),
			connect.WithClientOptions(opts...),
		),
		listConversations: connect.NewClient[ListConversationsRequest, ListConversationsResponse](
			httpClient,
			baseURL+ConversationServiceListConversationsProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("ListConversations")),
			connect.WithClientOptions(opts...),
		),
		deleteConversation: connect.NewClient[DeleteConversationRequest, Empty](
			httpClient,
			baseURL+ConversationServiceDeleteConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("DeleteConversation")),
			connect.WithClientOptions(opts...),
		),
		getMessages: connect.NewClient[GetMessagesRequest, GetMessagesResponse](
			httpClient,
			baseURL+ConversationServiceGetMessagesProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("GetMessages")),
			connect.WithClientOptions(opts...),
		),
		chat: connect.NewClient[ChatRequest, ChatEvent](
			httpClient,
			baseURL+ConversationServiceChatProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("Chat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// conversationServiceClient implements ConversationServiceClient.
type conversationServiceClient struct {
	createConversation *connect.Client[CreateConversationRequest, Conversation]
	getConversation    *connect.Client[GetConversationRequest, Conversation]
	listConversations  *connect.Client[ListConversationsRequest, ListConversationsResponse]
	deleteConversation *connect.Client[DeleteConversationRequest, Empty]
	getMessages        *connect.Client[GetMessagesRequest, GetMessagesResponse]
	chat               *connect.Client[ChatRequest, ChatEvent]
}

// CreateConversation calls blippy.conversation.ConversationService.CreateConversation.
func (c *conversationServiceClient) CreateConversation(ctx context.Context, req *connect.Request[CreateConversationRequest]) (*connect.Response[Conversation], error) {
	return c.createConversation.CallUnary(ctx, req)
}

// GetConversation calls blippy.conversation.ConversationService.GetConversation.
func (c *conversationServiceClient) GetConversation(ctx context.Context, req *connect.Request[GetConversationRequest]) (*connect.Response[Conversation], error) {
	return c.getConversation.CallUnary(ctx, req)
}

// ListConversations calls blippy.conversation.ConversationService.ListConversations.
func (c *conversationServiceClient) ListConversations(ctx context.Context, req *connect.Request[ListConversationsRequest]) (*connect.Response[ListConversationsResponse], error) {
	return c.listConversations.CallUnary(ctx, req)
}

// DeleteConversation calls blippy.conversation.ConversationService.DeleteConversation.
func (c *conversationServiceClient) DeleteConversation(ctx context.Context, req *connect.Request[DeleteConversationRequest]) (*connect.Response[Empty], error) {
	return c.deleteConversation.CallUnary(ctx, req)
}

// GetMessages calls blippy.conversation.ConversationService.GetMessages.
func (c *conversationServiceClient) GetMessages(ctx context.Context, req *connect.Request[GetMessagesRequest]) (*connect.Response[GetMessagesResponse], error) {
	return c.getMessages.CallUnary(ctx, req)
}

// Chat calls blippy.conversation.ConversationService.Chat.
func (c *conversationServiceClient) Chat(ctx context.Context, req *connect.Request[ChatRequest]) (*connect.ServerStreamForClient[ChatEvent], error) {
	return c.chat.CallServerStream(ctx, req)
}

// ConversationServiceHandler is an implementation of the blippy.conversation.ConversationService
// service.
type ConversationServiceHandler interface {
	CreateConversation(context.Context, *connect.Request[CreateConversationRequest]) (*connect.Response[Conversation], error)
	GetConversation(context.Context, *connect.Request[GetConversationRequest]) (*connect.Response[Conversation], error)
	ListConversations(context.Context, *connect.Request[ListConversationsRequest]) (*connect.Response[ListConversationsResponse], error)
	DeleteConversation(context.Context, *connect.Request[DeleteConversationRequest]) (*connect.Response[Empty], error)
	GetMessages(context.Context, *connect.Request[GetMessagesRequest]) (*connect.Response[GetMessagesResponse], error)
	Chat(context.Context, *connect.Request[ChatRequest], *connect.ServerStream[ChatEvent]) error
}

// NewConversationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConversationServiceHandler(svc ConversationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	conversationServiceMethods := File_conversation_conversation_proto.Services().ByName("ConversationService").Methods()
	conversationServiceCreateConversationHandler := connect.NewUnaryHandler(
		ConversationServiceCreateConversationProcedure,
		svc.CreateConversation,
		connect.WithSchema(conversationServiceMethods.ByName("CreateConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceGetConversationHandler := connect.NewUnaryHandler(
		ConversationServiceGetConversationProcedure,
		svc.GetConversation,
		connect.WithSchema(conversationServiceMethods.ByName("GetConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceListConversationsHandler := connect.NewUnaryHandler(
		ConversationServiceListConversationsProcedure,
		svc.ListConversations,
		connect.WithSchema(conversationServiceMethods.ByName("ListConversations")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceDeleteConversationHandler := connect.NewUnaryHandler(
		ConversationServiceDeleteConversationProcedure,
		svc.DeleteConversation,
		connect.WithSchema(conversationServiceMethods.ByName("DeleteConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceGetMessagesHandler := connect.NewUnaryHandler(
		ConversationServiceGetMessagesProcedure,
		svc.GetMessages,
		connect.WithSchema(conversationServiceMethods.ByName("GetMessages")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceChatHandler := connect.NewServerStreamHandler(
		ConversationServiceChatProcedure,
		svc.Chat,
		connect.WithSchema(conversationServiceMethods.ByName("Chat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blippy.conversation.ConversationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConversationServiceCreateConversationProcedure:
			conversationServiceCreateConversationHandler.ServeHTTP(w, r)
		case ConversationServiceGetConversationProcedure:
			conversationServiceGetConversationHandler.ServeHTTP(w, r)
		case ConversationServiceListConversationsProcedure:
			conversationServiceListConversationsHandler.ServeHTTP(w, r)
		case ConversationServiceDeleteConversationProcedure:
			conversationServiceDeleteConversationHandler.ServeHTTP(w, r)
		case ConversationServiceGetMessagesProcedure:
			conversationServiceGetMessagesHandler.ServeHTTP(w, r)
		case ConversationServiceChatProcedure:
			conversationServiceChatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConversationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConversationServiceHandler struct{}

func (UnimplementedConversationServiceHandler) CreateConversation(context.Context, *connect.Request[CreateConversationRequest]) (*connect.Response[Conversation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.conversation.ConversationService.CreateConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) GetConversation(context.Context, *connect.Request[GetConversationRequest]) (*connect.Response[Conversation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.conversation.ConversationService.GetConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) ListConversations(context.Context, *connect.Request[ListConversationsRequest]) (*connect.Response[ListConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.conversation.ConversationService.ListConversations is not implemented"))
}

func (UnimplementedConversationServiceHandler) DeleteConversation(context.Context, *connect.Request[DeleteConversationRequest]) (*connect.Response[Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.conversation.ConversationService.DeleteConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) GetMessages(context.Context, *connect.Request[GetMessagesRequest]) (*connect.Response[GetMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.conversation.ConversationService.GetMessages is not implemented"))
}

func (UnimplementedConversationServiceHandler) Chat(context.Context, *connect.Request[ChatRequest], *connect.ServerStream[ChatEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("blippy.conversation.ConversationService.Chat is not implemented"))
}
