// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fsroot/fsroot.proto

package fsroot

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilesystemRootServiceName is the fully-qualified name of the FilesystemRootService service.
	FilesystemRootServiceName = "blippy.fsroot.FilesystemRootService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilesystemRootServiceCreateFilesystemRootProcedure is the fully-qualified name of the
	// FilesystemRootService's CreateFilesystemRoot RPC.
	FilesystemRootServiceCreateFilesystemRootProcedure = "/blippy.fsroot.FilesystemRootService/CreateFilesystemRoot"
	// FilesystemRootServiceGetFilesystemRootProcedure is the fully-qualified name of the
	// FilesystemRootService's GetFilesystemRoot RPC.
	FilesystemRootServiceGetFilesystemRootProcedure = "/blippy.fsroot.FilesystemRootService/GetFilesystemRoot"
	// FilesystemRootServiceListFilesystemRootsProcedure is the fully-qualified name of the
	// FilesystemRootService's ListFilesystemRoots RPC.
	FilesystemRootServiceListFilesystemRootsProcedure = "/blippy.fsroot.FilesystemRootService/ListFilesystemRoots"
	// FilesystemRootServiceUpdateFilesystemRootProcedure is the fully-qualified name of the
	// FilesystemRootService's UpdateFilesystemRoot RPC.
	FilesystemRootServiceUpdateFilesystemRootProcedure = "/blippy.fsroot.FilesystemRootService/UpdateFilesystemRoot"
	// FilesystemRootServiceDeleteFilesystemRootProcedure is the fully-qualified name of the
	// FilesystemRootService's DeleteFilesystemRoot RPC.
	FilesystemRootServiceDeleteFilesystemRootProcedure = "/blippy.fsroot.FilesystemRootService/DeleteFilesystemRoot"
)

// FilesystemRootServiceClient is a client for the blippy.fsroot.FilesystemRootService service.
type FilesystemRootServiceClient interface {
	CreateFilesystemRoot(context.Context, *connect.Request[CreateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error)
	GetFilesystemRoot(context.Context, *connect.Request[GetFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error)
	ListFilesystemRoots(context.Context, *connect.Request[ListFilesystemRootsRequest]) (*connect.Response[ListFilesystemRootsResponse], error)
	UpdateFilesystemRoot(context.Context, *connect.Request[UpdateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error)
	DeleteFilesystemRoot(context.Context, *connect.Request[DeleteFilesystemRootRequest]) (*connect.Response[Empty], error)
}

// NewFilesystemRootServiceClient constructs a client for the blippy.fsroot.FilesystemRootService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilesystemRootServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FilesystemRootServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filesystemRootServiceMethods := File_fsroot_fsroot_proto.Services().ByName("FilesystemRootService").Methods()
	return &filesystemRootServiceClient{
		createFilesystemRoot: connect.NewClient[CreateFilesystemRootRequest, FilesystemRoot](
			httpClient,
			baseURL+FilesystemRootServiceCreateFilesystemRootProcedure,
			connect.WithSchema(filesystemRootServiceMethods.ByName("CreateFilesystemRoot")),
			connect.WithClientOptions(opts...),
		),
		getFilesystemRoot: connect.NewClient[GetFilesystemRootRequest, FilesystemRoot](
			httpClient,
			baseURL+FilesystemRootServiceGetFilesystemRootProcedure,
			connect.WithSchema(filesystemRootServiceMethods.ByName("GetFilesystemRoot")),
			connect.WithClientOptions(opts...),
		),
		listFilesystemRoots: connect.NewClient[ListFilesystemRootsRequest, ListFilesystemRootsResponse](
			httpClient,
			baseURL+FilesystemRootServiceListFilesystemRootsProcedure,
			connect.WithSchema(filesystemRootServiceMethods.ByName("ListFilesystemRoots")),
			connect.WithClientOptions(opts...),
		),
		updateFilesystemRoot: connect.NewClient[UpdateFilesystemRootRequest, FilesystemRoot](
			httpClient,
			baseURL+FilesystemRootServiceUpdateFilesystemRootProcedure,
			connect.WithSchema(filesystemRootServiceMethods.ByName("UpdateFilesystemRoot")),
			connect.WithClientOptions(opts...),
		),
		deleteFilesystemRoot: connect.NewClient[DeleteFilesystemRootRequest, Empty](
			httpClient,
			baseURL+FilesystemRootServiceDeleteFilesystemRootProcedure,
			connect.WithSchema(filesystemRootServiceMethods.ByName("DeleteFilesystemRoot")),
			connect.WithClientOptions(opts...),
		),
	}
}

// filesystemRootServiceClient implements FilesystemRootServiceClient.
type filesystemRootServiceClient struct {
	createFilesystemRoot *connect.Client[CreateFilesystemRootRequest, FilesystemRoot]
	getFilesystemRoot    *connect.Client[GetFilesystemRootRequest, FilesystemRoot]
	listFilesystemRoots  *connect.Client[ListFilesystemRootsRequest, ListFilesystemRootsResponse]
	updateFilesystemRoot *connect.Client[UpdateFilesystemRootRequest, FilesystemRoot]
	deleteFilesystemRoot *connect.Client[DeleteFilesystemRootRequest, Empty]
}

// CreateFilesystemRoot calls blippy.fsroot.FilesystemRootService.CreateFilesystemRoot.
func (c *filesystemRootServiceClient) CreateFilesystemRoot(ctx context.Context, req *connect.Request[CreateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error) {
	return c.createFilesystemRoot.CallUnary(ctx, req)
}

// GetFilesystemRoot calls blippy.fsroot.FilesystemRootService.GetFilesystemRoot.
func (c *filesystemRootServiceClient) GetFilesystemRoot(ctx context.Context, req *connect.Request[GetFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error) {
	return c.getFilesystemRoot.CallUnary(ctx, req)
}

// ListFilesystemRoots calls blippy.fsroot.FilesystemRootService.ListFilesystemRoots.
func (c *filesystemRootServiceClient) ListFilesystemRoots(ctx context.Context, req *connect.Request[ListFilesystemRootsRequest]) (*connect.Response[ListFilesystemRootsResponse], error) {
	return c.listFilesystemRoots.CallUnary(ctx, req)
}

// UpdateFilesystemRoot calls blippy.fsroot.FilesystemRootService.UpdateFilesystemRoot.
func (c *filesystemRootServiceClient) UpdateFilesystemRoot(ctx context.Context, req *connect.Request[UpdateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error) {
	return c.updateFilesystemRoot.CallUnary(ctx, req)
}

// DeleteFilesystemRoot calls blippy.fsroot.FilesystemRootService.DeleteFilesystemRoot.
func (c *filesystemRootServiceClient) DeleteFilesystemRoot(ctx context.Context, req *connect.Request[DeleteFilesystemRootRequest]) (*connect.Response[Empty], error) {
	return c.deleteFilesystemRoot.CallUnary(ctx, req)
}

// FilesystemRootServiceHandler is an implementation of the blippy.fsroot.FilesystemRootService
// service.
type FilesystemRootServiceHandler interface {
	CreateFilesystemRoot(context.Context, *connect.Request[CreateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error)
	GetFilesystemRoot(context.Context, *connect.Request[GetFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error)
	ListFilesystemRoots(context.Context, *connect.Request[ListFilesystemRootsRequest]) (*connect.Response[ListFilesystemRootsResponse], error)
	UpdateFilesystemRoot(context.Context, *connect.Request[UpdateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error)
	DeleteFilesystemRoot(context.Context, *connect.Request[DeleteFilesystemRootRequest]) (*connect.Response[Empty], error)
}

// NewFilesystemRootServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilesystemRootServiceHandler(svc FilesystemRootServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filesystemRootServiceMethods := File_fsroot_fsroot_proto.Services().ByName("FilesystemRootService").Methods()
	filesystemRootServiceCreateFilesystemRootHandler := connect.NewUnaryHandler(
		FilesystemRootServiceCreateFilesystemRootProcedure,
		svc.CreateFilesystemRoot,
		connect.WithSchema(filesystemRootServiceMethods.ByName("CreateFilesystemRoot")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemRootServiceGetFilesystemRootHandler := connect.NewUnaryHandler(
		FilesystemRootServiceGetFilesystemRootProcedure,
		svc.GetFilesystemRoot,
		connect.WithSchema(filesystemRootServiceMethods.ByName("GetFilesystemRoot")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemRootServiceListFilesystemRootsHandler := connect.NewUnaryHandler(
		FilesystemRootServiceListFilesystemRootsProcedure,
		svc.ListFilesystemRoots,
		connect.WithSchema(filesystemRootServiceMethods.ByName("ListFilesystemRoots")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemRootServiceUpdateFilesystemRootHandler := connect.NewUnaryHandler(
		FilesystemRootServiceUpdateFilesystemRootProcedure,
		svc.UpdateFilesystemRoot,
		connect.WithSchema(filesystemRootServiceMethods.ByName("UpdateFilesystemRoot")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemRootServiceDeleteFilesystemRootHandler := connect.NewUnaryHandler(
		FilesystemRootServiceDeleteFilesystemRootProcedure,
		svc.DeleteFilesystemRoot,
		connect.WithSchema(filesystemRootServiceMethods.ByName("DeleteFilesystemRoot")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blippy.fsroot.FilesystemRootService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilesystemRootServiceCreateFilesystemRootProcedure:
			filesystemRootServiceCreateFilesystemRootHandler.ServeHTTP(w, r)
		case FilesystemRootServiceGetFilesystemRootProcedure:
			filesystemRootServiceGetFilesystemRootHandler.ServeHTTP(w, r)
		case FilesystemRootServiceListFilesystemRootsProcedure:
			filesystemRootServiceListFilesystemRootsHandler.ServeHTTP(w, r)
		case FilesystemRootServiceUpdateFilesystemRootProcedure:
			filesystemRootServiceUpdateFilesystemRootHandler.ServeHTTP(w, r)
		case FilesystemRootServiceDeleteFilesystemRootProcedure:
			filesystemRootServiceDeleteFilesystemRootHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilesystemRootServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFilesystemRootServiceHandler struct{}

func (UnimplementedFilesystemRootServiceHandler) CreateFilesystemRoot(context.Context, *connect.Request[CreateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.fsroot.FilesystemRootService.CreateFilesystemRoot is not implemented"))
}

func (UnimplementedFilesystemRootServiceHandler) GetFilesystemRoot(context.Context, *connect.Request[GetFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.fsroot.FilesystemRootService.GetFilesystemRoot is not implemented"))
}

func (UnimplementedFilesystemRootServiceHandler) ListFilesystemRoots(context.Context, *connect.Request[ListFilesystemRootsRequest]) (*connect.Response[ListFilesystemRootsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.fsroot.FilesystemRootService.ListFilesystemRoots is not implemented"))
}

func (UnimplementedFilesystemRootServiceHandler) UpdateFilesystemRoot(context.Context, *connect.Request[UpdateFilesystemRootRequest]) (*connect.Response[FilesystemRoot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.fsroot.FilesystemRootService.UpdateFilesystemRoot is not implemented"))
}

func (UnimplementedFilesystemRootServiceHandler) DeleteFilesystemRoot(context.Context, *connect.Request[DeleteFilesystemRootRequest]) (*connect.Response[Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blippy.fsroot.FilesystemRootService.DeleteFilesystemRoot is not implemented"))
}
