// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fsroot/fsroot.proto

package fsroot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilesystemRoot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemRoot) Reset() {
	*x = FilesystemRoot{}
	mi := &file_fsroot_fsroot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemRoot) ProtoMessage() {}

func (x *FilesystemRoot) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemRoot.ProtoReflect.Descriptor instead.
func (*FilesystemRoot) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{0}
}

func (x *FilesystemRoot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilesystemRoot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilesystemRoot) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilesystemRoot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FilesystemRoot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FilesystemRoot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateFilesystemRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilesystemRootRequest) Reset() {
	*x = CreateFilesystemRootRequest{}
	mi := &file_fsroot_fsroot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilesystemRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilesystemRootRequest) ProtoMessage() {}

func (x *CreateFilesystemRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilesystemRootRequest.ProtoReflect.Descriptor instead.
func (*CreateFilesystemRootRequest) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFilesystemRootRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFilesystemRootRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFilesystemRootRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetFilesystemRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesystemRootRequest) Reset() {
	*x = GetFilesystemRootRequest{}
	mi := &file_fsroot_fsroot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesystemRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesystemRootRequest) ProtoMessage() {}

func (x *GetFilesystemRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesystemRootRequest.ProtoReflect.Descriptor instead.
func (*GetFilesystemRootRequest) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{2}
}

func (x *GetFilesystemRootRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFilesystemRootsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemRootsRequest) Reset() {
	*x = ListFilesystemRootsRequest{}
	mi := &file_fsroot_fsroot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemRootsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemRootsRequest) ProtoMessage() {}

func (x *ListFilesystemRootsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemRootsRequest.ProtoReflect.Descriptor instead.
func (*ListFilesystemRootsRequest) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{3}
}

type ListFilesystemRootsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*FilesystemRoot      `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemRootsResponse) Reset() {
	*x = ListFilesystemRootsResponse{}
	mi := &file_fsroot_fsroot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemRootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemRootsResponse) ProtoMessage() {}

func (x *ListFilesystemRootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemRootsResponse.ProtoReflect.Descriptor instead.
func (*ListFilesystemRootsResponse) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesystemRootsResponse) GetRoots() []*FilesystemRoot {
	if x != nil {
		return x.Roots
	}
	return nil
}

type UpdateFilesystemRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilesystemRootRequest) Reset() {
	*x = UpdateFilesystemRootRequest{}
	mi := &file_fsroot_fsroot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilesystemRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilesystemRootRequest) ProtoMessage() {}

func (x *UpdateFilesystemRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilesystemRootRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilesystemRootRequest) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFilesystemRootRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFilesystemRootRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFilesystemRootRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateFilesystemRootRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteFilesystemRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilesystemRootRequest) Reset() {
	*x = DeleteFilesystemRootRequest{}
	mi := &file_fsroot_fsroot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilesystemRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilesystemRootRequest) ProtoMessage() {}

func (x *DeleteFilesystemRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilesystemRootRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilesystemRootRequest) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFilesystemRootRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_fsroot_fsroot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_fsroot_fsroot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_fsroot_fsroot_proto_rawDescGZIP(), []int{7}
}

var File_fsroot_fsroot_proto protoreflect.FileDescriptor

const file_fsroot_fsroot_proto_rawDesc = "" +
	"\n" +
	"\x13fsroot/fsroot.proto\x12\rblippy.fsroot\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n" +
	"\x0eFilesystemRoot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\x1bCreateFilesystemRootRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"*\n" +
	"\x18GetFilesystemRootRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x1aListFilesystemRootsRequest\"R\n" +
	"\x1bListFilesystemRootsResponse\x123\n" +
	"\x05roots\x18\x01 \x03(\v2\x1d.blippy.fsroot.FilesystemRootR\x05roots\"w\n" +
	"\x1bUpdateFilesystemRootRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"-\n" +
	"\x1bDeleteFilesystemRootRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\x82\x04\n" +
	"\x15FilesystemRootService\x12a\n" +
	"\x14CreateFilesystemRoot\x12*.blippy.fsroot.CreateFilesystemRootRequest\x1a\x1d.blippy.fsroot.FilesystemRoot\x12[\n" +
	"\x11GetFilesystemRoot\x12'.blippy.fsroot.GetFilesystemRootRequest\x1a\x1d.blippy.fsroot.FilesystemRoot\x12l\n" +
	"\x13ListFilesystemRoots\x12).blippy.fsroot.ListFilesystemRootsRequest\x1a*.blippy.fsroot.ListFilesystemRootsResponse\x12a\n" +
	"\x14UpdateFilesystemRoot\x12*.blippy.fsroot.UpdateFilesystemRootRequest\x1a\x1d.blippy.fsroot.FilesystemRoot\x12X\n" +
	"\x14DeleteFilesystemRoot\x12*.blippy.fsroot.DeleteFilesystemRootRequest\x1a\x14.blippy.fsroot.EmptyB,Z*github.com/dstotijn/blippy/internal/fsrootb\x06proto3"

var (
	file_fsroot_fsroot_proto_rawDescOnce sync.Once
	file_fsroot_fsroot_proto_rawDescData []byte
)

func file_fsroot_fsroot_proto_rawDescGZIP() []byte {
	file_fsroot_fsroot_proto_rawDescOnce.Do(func() {
		file_fsroot_fsroot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fsroot_fsroot_proto_rawDesc), len(file_fsroot_fsroot_proto_rawDesc)))
	})
	return file_fsroot_fsroot_proto_rawDescData
}

var file_fsroot_fsroot_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fsroot_fsroot_proto_goTypes = []any{
	(*FilesystemRoot)(nil),              // 0: blippy.fsroot.FilesystemRoot
	(*CreateFilesystemRootRequest)(nil), // 1: blippy.fsroot.CreateFilesystemRootRequest
	(*GetFilesystemRootRequest)(nil),    // 2: blippy.fsroot.GetFilesystemRootRequest
	(*ListFilesystemRootsRequest)(nil),  // 3: blippy.fsroot.ListFilesystemRootsRequest
	(*ListFilesystemRootsResponse)(nil), // 4: blippy.fsroot.ListFilesystemRootsResponse
	(*UpdateFilesystemRootRequest)(nil), // 5: blippy.fsroot.UpdateFilesystemRootRequest
	(*DeleteFilesystemRootRequest)(nil), // 6: blippy.fsroot.DeleteFilesystemRootRequest
	(*Empty)(nil),                       // 7: blippy.fsroot.Empty
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_fsroot_fsroot_proto_depIdxs = []int32{
	8, // 0: blippy.fsroot.FilesystemRoot.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: blippy.fsroot.FilesystemRoot.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: blippy.fsroot.ListFilesystemRootsResponse.roots:type_name -> blippy.fsroot.FilesystemRoot
	1, // 3: blippy.fsroot.FilesystemRootService.CreateFilesystemRoot:input_type -> blippy.fsroot.CreateFilesystemRootRequest
	2, // 4: blippy.fsroot.FilesystemRootService.GetFilesystemRoot:input_type -> blippy.fsroot.GetFilesystemRootRequest
	3, // 5: blippy.fsroot.FilesystemRootService.ListFilesystemRoots:input_type -> blippy.fsroot.ListFilesystemRootsRequest
	5, // 6: blippy.fsroot.FilesystemRootService.UpdateFilesystemRoot:input_type -> blippy.fsroot.UpdateFilesystemRootRequest
	6, // 7: blippy.fsroot.FilesystemRootService.DeleteFilesystemRoot:input_type -> blippy.fsroot.DeleteFilesystemRootRequest
	0, // 8: blippy.fsroot.FilesystemRootService.CreateFilesystemRoot:output_type -> blippy.fsroot.FilesystemRoot
	0, // 9: blippy.fsroot.FilesystemRootService.GetFilesystemRoot:output_type -> blippy.fsroot.FilesystemRoot
	4, // 10: blippy.fsroot.FilesystemRootService.ListFilesystemRoots:output_type -> blippy.fsroot.ListFilesystemRootsResponse
	0, // 11: blippy.fsroot.FilesystemRootService.UpdateFilesystemRoot:output_type -> blippy.fsroot.FilesystemRoot
	7, // 12: blippy.fsroot.FilesystemRootService.DeleteFilesystemRoot:output_type -> blippy.fsroot.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fsroot_fsroot_proto_init() }
func file_fsroot_fsroot_proto_init() {
	if File_fsroot_fsroot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fsroot_fsroot_proto_rawDesc), len(file_fsroot_fsroot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fsroot_fsroot_proto_goTypes,
		DependencyIndexes: file_fsroot_fsroot_proto_depIdxs,
		MessageInfos:      file_fsroot_fsroot_proto_msgTypes,
	}.Build()
	File_fsroot_fsroot_proto = out.File
	file_fsroot_fsroot_proto_goTypes = nil
	file_fsroot_fsroot_proto_depIdxs = nil
}
