// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file notification/notification.proto (package blippy.notification, syntax proto3)
/* eslint-disable */

import { NotificationChannelService } from "./notification_pb";

/**
 * @generated from rpc blippy.notification.NotificationChannelService.CreateNotificationChannel
 */
export const createNotificationChannel = NotificationChannelService.method.createNotificationChannel;

/**
 * @generated from rpc blippy.notification.NotificationChannelService.GetNotificationChannel
 */
export const getNotificationChannel = NotificationChannelService.method.getNotificationChannel;

/**
 * @generated from rpc blippy.notification.NotificationChannelService.ListNotificationChannels
 */
export const listNotificationChannels = NotificationChannelService.method.listNotificationChannels;

/**
 * @generated from rpc blippy.notification.NotificationChannelService.UpdateNotificationChannel
 */
export const updateNotificationChannel = NotificationChannelService.method.updateNotificationChannel;

/**
 * @generated from rpc blippy.notification.NotificationChannelService.DeleteNotificationChannel
 */
export const deleteNotificationChannel = NotificationChannelService.method.deleteNotificationChannel;
