/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TriggersIndexRouteImport } from './routes/triggers/index'
import { Route as RootsIndexRouteImport } from './routes/roots/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as TriggersNewRouteImport } from './routes/triggers/new'
import { Route as TriggersTriggerIdRouteImport } from './routes/triggers/$triggerId'
import { Route as RootsNewRouteImport } from './routes/roots/new'
import { Route as RootsRootIdRouteImport } from './routes/roots/$rootId'
import { Route as NotificationsNewRouteImport } from './routes/notifications/new'
import { Route as NotificationsChannelIdRouteImport } from './routes/notifications/$channelId'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents/$agentId/index'
import { Route as AgentsAgentIdSettingsRouteImport } from './routes/agents/$agentId/settings'
import { Route as AgentsAgentIdConversationIdRouteImport } from './routes/agents/$agentId/$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersIndexRoute = TriggersIndexRouteImport.update({
  id: '/triggers/',
  path: '/triggers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsIndexRoute = RootsIndexRouteImport.update({
  id: '/roots/',
  path: '/roots/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersNewRoute = TriggersNewRouteImport.update({
  id: '/triggers/new',
  path: '/triggers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersTriggerIdRoute = TriggersTriggerIdRouteImport.update({
  id: '/triggers/$triggerId',
  path: '/triggers/$triggerId',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsNewRoute = RootsNewRouteImport.update({
  id: '/roots/new',
  path: '/roots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsRootIdRoute = RootsRootIdRouteImport.update({
  id: '/roots/$rootId',
  path: '/roots/$rootId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsNewRoute = NotificationsNewRouteImport.update({
  id: '/notifications/new',
  path: '/notifications/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsChannelIdRoute = NotificationsChannelIdRouteImport.update({
  id: '/notifications/$channelId',
  path: '/notifications/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdSettingsRoute = AgentsAgentIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdConversationIdRoute =
  AgentsAgentIdConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AgentsAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/notifications/$channelId': typeof NotificationsChannelIdRoute
  '/notifications/new': typeof NotificationsNewRoute
  '/roots/$rootId': typeof RootsRootIdRoute
  '/roots/new': typeof RootsNewRoute
  '/triggers/$triggerId': typeof TriggersTriggerIdRoute
  '/triggers/new': typeof TriggersNewRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/roots/': typeof RootsIndexRoute
  '/triggers/': typeof TriggersIndexRoute
  '/agents/$agentId/$conversationId': typeof AgentsAgentIdConversationIdRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/new': typeof AgentsNewRoute
  '/notifications/$channelId': typeof NotificationsChannelIdRoute
  '/notifications/new': typeof NotificationsNewRoute
  '/roots/$rootId': typeof RootsRootIdRoute
  '/roots/new': typeof RootsNewRoute
  '/triggers/$triggerId': typeof TriggersTriggerIdRoute
  '/triggers/new': typeof TriggersNewRoute
  '/notifications': typeof NotificationsIndexRoute
  '/roots': typeof RootsIndexRoute
  '/triggers': typeof TriggersIndexRoute
  '/agents/$agentId/$conversationId': typeof AgentsAgentIdConversationIdRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/notifications/$channelId': typeof NotificationsChannelIdRoute
  '/notifications/new': typeof NotificationsNewRoute
  '/roots/$rootId': typeof RootsRootIdRoute
  '/roots/new': typeof RootsNewRoute
  '/triggers/$triggerId': typeof TriggersTriggerIdRoute
  '/triggers/new': typeof TriggersNewRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/roots/': typeof RootsIndexRoute
  '/triggers/': typeof TriggersIndexRoute
  '/agents/$agentId/$conversationId': typeof AgentsAgentIdConversationIdRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/notifications/$channelId'
    | '/notifications/new'
    | '/roots/$rootId'
    | '/roots/new'
    | '/triggers/$triggerId'
    | '/triggers/new'
    | '/notifications/'
    | '/roots/'
    | '/triggers/'
    | '/agents/$agentId/$conversationId'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/new'
    | '/notifications/$channelId'
    | '/notifications/new'
    | '/roots/$rootId'
    | '/roots/new'
    | '/triggers/$triggerId'
    | '/triggers/new'
    | '/notifications'
    | '/roots'
    | '/triggers'
    | '/agents/$agentId/$conversationId'
    | '/agents/$agentId/settings'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/notifications/$channelId'
    | '/notifications/new'
    | '/roots/$rootId'
    | '/roots/new'
    | '/triggers/$triggerId'
    | '/triggers/new'
    | '/notifications/'
    | '/roots/'
    | '/triggers/'
    | '/agents/$agentId/$conversationId'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
  NotificationsChannelIdRoute: typeof NotificationsChannelIdRoute
  NotificationsNewRoute: typeof NotificationsNewRoute
  RootsRootIdRoute: typeof RootsRootIdRoute
  RootsNewRoute: typeof RootsNewRoute
  TriggersTriggerIdRoute: typeof TriggersTriggerIdRoute
  TriggersNewRoute: typeof TriggersNewRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  RootsIndexRoute: typeof RootsIndexRoute
  TriggersIndexRoute: typeof TriggersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/': {
      id: '/triggers/'
      path: '/triggers'
      fullPath: '/triggers/'
      preLoaderRoute: typeof TriggersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots/': {
      id: '/roots/'
      path: '/roots'
      fullPath: '/roots/'
      preLoaderRoute: typeof RootsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/new': {
      id: '/triggers/new'
      path: '/triggers/new'
      fullPath: '/triggers/new'
      preLoaderRoute: typeof TriggersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/$triggerId': {
      id: '/triggers/$triggerId'
      path: '/triggers/$triggerId'
      fullPath: '/triggers/$triggerId'
      preLoaderRoute: typeof TriggersTriggerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots/new': {
      id: '/roots/new'
      path: '/roots/new'
      fullPath: '/roots/new'
      preLoaderRoute: typeof RootsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots/$rootId': {
      id: '/roots/$rootId'
      path: '/roots/$rootId'
      fullPath: '/roots/$rootId'
      preLoaderRoute: typeof RootsRootIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/new': {
      id: '/notifications/new'
      path: '/notifications/new'
      fullPath: '/notifications/new'
      preLoaderRoute: typeof NotificationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/$channelId': {
      id: '/notifications/$channelId'
      path: '/notifications/$channelId'
      fullPath: '/notifications/$channelId'
      preLoaderRoute: typeof NotificationsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/settings': {
      id: '/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/agents/$agentId/settings'
      preLoaderRoute: typeof AgentsAgentIdSettingsRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/$conversationId': {
      id: '/agents/$agentId/$conversationId'
      path: '/$conversationId'
      fullPath: '/agents/$agentId/$conversationId'
      preLoaderRoute: typeof AgentsAgentIdConversationIdRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdConversationIdRoute: typeof AgentsAgentIdConversationIdRoute
  AgentsAgentIdSettingsRoute: typeof AgentsAgentIdSettingsRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdConversationIdRoute: AgentsAgentIdConversationIdRoute,
  AgentsAgentIdSettingsRoute: AgentsAgentIdSettingsRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
  NotificationsChannelIdRoute: NotificationsChannelIdRoute,
  NotificationsNewRoute: NotificationsNewRoute,
  RootsRootIdRoute: RootsRootIdRoute,
  RootsNewRoute: RootsNewRoute,
  TriggersTriggerIdRoute: TriggersTriggerIdRoute,
  TriggersNewRoute: TriggersNewRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  RootsIndexRoute: RootsIndexRoute,
  TriggersIndexRoute: TriggersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
