// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file conversation/conversation.proto (package blippy.conversation, syntax proto3)
/* eslint-disable */

import { ConversationService } from "./conversation_pb";

/**
 * @generated from rpc blippy.conversation.ConversationService.CreateConversation
 */
export const createConversation = ConversationService.method.createConversation;

/**
 * @generated from rpc blippy.conversation.ConversationService.GetConversation
 */
export const getConversation = ConversationService.method.getConversation;

/**
 * @generated from rpc blippy.conversation.ConversationService.ListConversations
 */
export const listConversations = ConversationService.method.listConversations;

/**
 * @generated from rpc blippy.conversation.ConversationService.DeleteConversation
 */
export const deleteConversation = ConversationService.method.deleteConversation;

/**
 * @generated from rpc blippy.conversation.ConversationService.GetMessages
 */
export const getMessages = ConversationService.method.getMessages;
